In [ ]:
Requesting the data and putting into CSV file:

In [ ]:
# #12th June 2020 - 8th March 2023

# import requests

# url = "https://lunarcrush.com/api3/coins/1/time-series?interval=all&start=%091591912800&bucket=day&data_points=1000"
# headers = {
#   'Authorization': 'Bearer czafphn2g5ln3tzinz5qd6bkxlf2f0y70cun8xs2r'

# response = requests.request("GET", url, headers=headers)
# response

# print(response.text.encode('utf8'))

# call = response.text.encode('utf8')

# response.content

# data1 = response.json()

# data1["timeSeries"]

# df = pd.json_normalize(data1["timeSeries"])

# df.to_csv('BitcoinLunarData', index=False)

In [ ]:
df_luna = pd.read_csv('BitcoinLunarData')

In [ ]:
#12th June 2020 - September 16th 2017

# import requests

# url = "https://lunarcrush.com/api3/coins/1/time-series?interval=1d&start=%091505512800&bucket=day&data_points=1000"
# headers = {
#   'Authorization': 'Bearer czafphn2g5ln3tzinz5qd6bkxlf2f0y70cun8xs2r'
# }

# response2 = requests.request("GET", url, headers=headers)

# print(response2.text.encode('utf8'))

# print(response2.text.encode('utf8'))

# call2 = response2.text.encode('utf8')

# response2.content

# data2 = response2.json()

# data2["timeSeries"]

# df2 = pd.json_normalize(data2["timeSeries"])

# df2.to_csv('BitcoinLunarData2', index=False)

In [ ]:
df2_luna = pd.read_csv('BitcoinLunarData2')

In [ ]:
#Finding the point where tweets has NaN values
num_nan_tweets = df2_luna['tweets'].isnull().sum()
num_nan_tweets

In [ ]:
#Dropping rows beyond which there are no tweet data
df2dropped_luna = df2_luna.drop(index=df2_luna.index[:712])
df2dropped_luna

In [ ]:
#Merging the older and more recent dataframes
merged_df = pd.concat([df2dropped_luna, df_luna], ignore_index=True)
merged_df.head()

In [ ]:
#Creating a dattime column by converting the UNIX time format
merged_df['date'] = pd.to_datetime(merged_df['time'], unit='s')
merged_df.head()

In [ ]:
#Creating a Day of the Month column 
merged_df['Day of Month'] = merged_df['date'].dt.day
merged_df.head()

In [ ]:
#Creating a month column 
merged_df['month'] = merged_df['date'].dt.month
merged_df.head()

In [ ]:
#Creating a % change column
merged_df['Daily % Change'] = merged_df['close'].pct_change() * 100
merged_df

In [ ]:
#Dropping Asset id column 
merged_df.drop('asset_id', axis=1, inplace=True)
merged_df

In [ ]:
#Indexing to date
merged_df.set_index('date', inplace=True)
merged_df

In [ ]:
#Exporting to CSV
merged_df.to_csv('merged_df', index=False)

In [28]:
# #Display all columns of data 

# from IPython.display import display
# pd.options.display.max_columns = None
# display(df)

,asset_id,time,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_followers,tweet_quotes,tweet_retweets,tweet_replies,tweet_favorites,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,sentiment_absolute,sentiment_relative,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,alt_rank,alt_rank_30d,alt_rank_hour_average,market_cap_rank,percent_change_24h_rank,volume_24h_rank,social_volume_24h_rank,social_score_24h_rank,medium,youtube,social_contributors,influential_content,influential_content_score,sma_50,sma_100,sma_200,social_volume,social_volume_global,social_dominance,market_cap_global,market_dominance
0,1,1591920000,9320.690855,9480.843789,9540.465393,9285.851404,2.980465e+10,2.261056e+10,1.744749e+11,18402731,30913,18049,1119.0,7416.0,1034.0,4490.0,106861,18926,407356377,2163,33471,12938,66854,2896,6046,19685,69973,8261,17248973,38055926,52842801,279445992,19878111,407514622,3.7,3,90,None,1165,2.9,3.9,3.4,69.2,0.023276,68,1,42.71,1,725,2,1,1,27.0,60.0,23537,NaN,NaN,9189.861282,7983.907717,8180.363379,128228,264995,48.388838,2.879446e+11,60.593227
1,1,1592006400,9480.735750,9475.277338,9493.211715,9396.009394,2.305366e+10,1.756432e+10,1.743818e+11,18403818,30023,16056,1038.0,3728.0,880.0,2645.0,100263,17641,298853834,1571,26604,12975,60335,2239,4205,22596,63319,7904,8088891,19789079,56818428,195883167,18375754,298991715,3.7,3,92,None,776,2.7,4.0,3.3,68.5,0.007402,133,1,104.63,1,1062,2,1,1,25.0,256.0,24588,NaN,NaN,9228.348808,7987.872862,8191.647909,119013,243804,48.815032,2.891715e+11,60.303947
2,1,1592092800,9477.554037,9386.787892,9482.270936,9347.593793,2.274307e+10,1.899173e+10,1.727632e+11,18404243,29124,16751,845.0,3162.0,848.0,2586.0,94651,14795,296795442,1782,27660,11798,57236,2424,4391,17473,61834,8529,6356561,21785156,50390644,201929002,16432555,296928790,3.7,3,91,None,717,3.0,3.4,3.0,65.8,0.003269,51,1,82.13,1,957,2,1,1,24.0,571.0,21320,NaN,NaN,9264.685845,7990.515285,8200.923530,113812,225466,50.478564,2.843811e+11,60.750615
3,1,1592179200,9386.035291,9450.701987,9504.860065,8990.175947,3.664421e+10,2.669970e+10,1.739476e+11,18404950,32183,20378,1242.0,4312.0,1301.0,4094.0,105986,16578,414932968,2253,35297,16531,86925,3172,5352,21023,67895,8544,16227483,26549295,58713090,295172800,18411306,415114563,3.7,3,90,None,1074,3.2,4.2,3.1,71.0,0.012543,30,1,27.67,1,637,2,1,1,30.0,310.0,24178,NaN,NaN,9300.102541,7995.922769,8210.861509,129981,247403,52.538166,2.833964e+11,61.379608
4,1,1592265600,9454.266431,9538.024374,9579.430375,9400.445008,2.862811e+10,2.156554e+10,1.755640e+11,18405843,32100,19499,1125.0,4421.0,1125.0,3996.0,101197,17243,465450803,2070,26721,9957,70771,3230,4385,22833,61062,9687,91135731,24720292,61288848,274302648,14112803,465600839,3.7,3,90,None,1072,3.0,4.3,3.2,71.1,0.016491,63,1,54.29,1,815,2,1,1,17.0,151.0,25935,NaN,NaN,9334.951012,8010.221850,8219.745413,124018,263058,47.144736,2.881761e+11,60.922456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,1677888000,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255,4509,847.0,3405.0,2308.0,5591.0,267079,155619,926458015,3878,64823,36844,206599,498,9913,120831,133465,2372,7304761,81552672,307309761,520593633,10009332,926831410,3.5,3,93,None,155,1.0,3.0,1.0,42.4,0.020725,137,22,261.83,1,2794,2,2,1,19.0,382.0,155477,809.0,629808.0,22921.778114,19968.458775,19725.154453,274898,2630450,10.450607,1.028053e+12,41.982981
996,1,1677974400,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091,4141,716.0,6987.0,2513.0,6434.0,268189,174436,875175325,21741,59450,36262,224585,450,9059,124496,131222,2962,2287570,57981678,329460461,476534730,9252924,875571875,3.5,3,93,None,127,1.0,3.0,1.0,42.4,0.014853,14,64,46.33,1,803,2,1,1,5.0,371.0,162513,888.0,702934.0,22950.962403,20027.595507,19720.652033,275686,2241463,12.299378,1.022768e+12,42.357236
997,1,1678060800,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697,6679,1105.0,4810.0,2847.0,10706.0,359141,222373,1197014726,13853,90663,48067,300224,510,11580,150406,193006,3638,8728612,73404851,440109724,657819860,17404481,1197537746,3.5,3,94,None,297,1.0,3.0,1.0,42.6,0.002277,40,25,109.25,1,3118,2,2,1,9.0,469.0,231981,1359.0,1115135.0,22981.941569,20087.250271,19716.737125,370069,2278351,16.242844,1.024951e+12,42.257871
998,1,1678147200,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540,6450,941.0,3944.0,2651.0,7502.0,344943,180947,1374308038,4797,79405,46217,261429,507,11814,137035,192830,2757,10545582,72733817,592071450,681497291,17851746,1374770872,3.5,3,94,None,335,1.0,3.0,1.0,42.7,0.003805,65,60,158.58,1,3154,2,1,1,12.0,474.0,207784,1318.0,1062812.0,23002.944295,20145.001693,19723.448202,355320,2244864,15.828130,1.024529e+12,41.881735
999,1,1678233600,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377,6215,983.0,4585.0,3651.0,8470.0,267005,207452,1131439670,4434,71128,42789,253187,777,10301,93111,160587,2229,3439410,100168088,333766714,687105359,7331637,1131879640,3.6,3,94,None,312,1.0,3.0,1.0,43.0,0.007676,58,44,142.25,1,3214,2,2,1,5.0,481.0,186460,1240.0,973915.0,23014.075507,20200.009267,19726.208299,278166,2224407,12.505176,1.017419e+12,41.224072

In [141]:
# # Import pandas library
# import pandas as pd


# from pytrends.request import TrendReq

# pytrends = TrendReq(hl='en-US', tz=360, timeout=(10,25), proxies=['https://34.203.233.13:80',], retries=2, backoff_factor=0.1, requests_args={'verify':False})


# # Set the keyword and timeframe
# keyword = 'bitcoin'
# timeframe = '2022-08-29 2023-03-08'

# # Build the payload for the interest over time data
# pytrends.build_payload(kw_list=[keyword], timeframe=timeframe)

# # Get the interest over time data
# interest_over_time_df = pytrends.interest_over_time()

# # Select the column with daily search volume values
# daily_interest_df = interest_over_time_df[[keyword]]

# # Rename the column to "Daily Interest"
# daily_interest_df.rename(columns={keyword: 'Daily Interest'}, inplace=True)

# # Convert the index to a datetime object
# daily_interest_df.index = pd.to_datetime(daily_interest_df.index)

# # Print the resulting DataFrame
# print(daily_interest_df)

In [138]:
# import yfinance as yf
# import pandas as pd

# # Set the start and end dates
# start_date = '2019-08-29'
# end_date = '2023-03-08'

# # Get the S&P 500 daily performance data
# sp500_df = yf.download('^GSPC', start=start_date, end=end_date, progress=False)
# sp500_daily_performance = (sp500_df['Close'] - sp500_df['Open']) / sp500_df['Open'] * 100

# # Get the NASDAQ 100 daily performance data
# nasdaq100_df = yf.download('^NDX', start=start_date, end=end_date, progress=False)
# nasdaq100_daily_performance = (nasdaq100_df['Close'] - nasdaq100_df['Open']) / nasdaq100_df['Open'] * 100

# # Get the treasury bond rate data
# treasury_bond_rates_df = yf.download('^TNX', start=start_date, end=end_date, progress=False)
# treasury_5yr_bond_rate = treasury_bond_rates_df['Close'].resample('D').last().ffill()
# treasury_10yr_bond_rate = treasury_bond_rates_df['Close'].resample('D').last().ffill()
# treasury_30yr_bond_rate = treasury_bond_rates_df['Close'].resample('D').last().ffill()

# # Get the 1-year treasury bond rate data
# treasury_1yr_bond_rates_df = yf.download('^IRX', start=start_date, end=end_date, progress=False)
# treasury_1yr_bond_rate = treasury_1yr_bond_rates_df['Close'].resample('D').last().ffill()

# # Get the bitcoin futures data
# bitcoin_futures_df = yf.download('BTC=F', start=start_date, end=end_date, progress=False)
# bitcoin_futures_volume = bitcoin_futures_df['Volume']
# bitcoin_futures_daily_returns = (bitcoin_futures_df['Close'] - bitcoin_futures_df['Open']) / bitcoin_futures_df['Open'] * 100
# bitcoin_futures_volatility = bitcoin_futures_daily_returns.std()

# # Combine the data into a single DataFrame
# data = {'S&P 500 Daily Performance': sp500_daily_performance,
#         'NASDAQ 100 Daily Performance': nasdaq100_daily_performance,
#         '1-Year Treasury Bond Rate': treasury_1yr_bond_rate,
#         '5-Year Treasury Bond Rate': treasury_5yr_bond_rate,
#         '10-Year Treasury Bond Rate': treasury_10yr_bond_rate, 
#         '30-Year Treasury Bond Rate': treasury_30yr_bond_rate,
#         'Bitcoin Futures Volume' : bitcoin_futures_volume, 
#         'Bitcoin Futures Returns' : bitcoin_futures_daily_returns,
#         'Bitcoin Futures Volatility': bitcoin_futures_volatility}

# financial_data4_df = pd.DataFrame(data)

# # Print the resulting DataFrame
# print(financial_data4_df)

In [75]:
# ## IMPORTING LIBRARIES
# from pytrends.request import TrendReq
# if "datetime" not in dir():
#     import datetime
#     from dateutil.relativedelta import relativedelta

# def trend_to_absolute(kws, avg, fr, to):
#     '''
#     Calculates the dayly search volume calculated from a reference search keyword
#     Arguments:
#         kws: list.
#             list of keywords with the reference keyword in the first place (max: 5 keywords)
#         avg: int. 
#             Average monthly search volume for a reference keyword in a period
#         fr: str.x
#             date in YYYY-MM-DD format (start date of the average monthy search volume)
#         to: str.
#             date in YYYY-MM-DD format (end date of the average monthy search volume)
#     Returns a dataframe with absoulute search volume
#     '''
#     d_ls = to.split("-")
#     dto = datetime.datetime(int(d_ls[0]), int(d_ls[1]), int(d_ls[2]))
#     d_ls = fr.split("-")
#     dfr = datetime.datetime(int(d_ls[0]), int(d_ls[1]), int(d_ls[2]))
#     dif_date = relativedelta(dto,dfr)
#     months = dif_date.months
#     if dif_date.days > 15:
#         months+=1
#     total_search = avg*months
#     pytrend = TrendReq()
#     pytrend.build_payload(kw_list=kws, timeframe=f'{fr} {to}')
#     df = pytrend.interest_over_time()
#     rel=int(total_search/df[kws[0]].sum())
#     for kw in kws:
#         df[kw] = df[kw]*rel
#     return df

In [151]:
# trend_to_absolute('bitcoin', 30, '29-08-2019', '08-03-2023')

In [101]:
import pandas as pd

# Assume merged_df is the DataFrame to which you want to add columns from financial_data4_df
# financial_data4_df is assumed to have a date index

# Load financial_data4_df


# Merge the two DataFrames based on their common date index
merged_df = merged_df.merge(financial_data4_df, left_index=True, right_index=True)

# Drop the index of financial_data_df
merged_df.reset_index(drop=True, inplace=True)

# Print the resulting DataFrame
print(merged_df)

TypeError: Cannot join tz-naive with tz-aware DatetimeIndex

In [102]:
# Reset the index of financial_data4_df
financial_data4_df = financial_data4_df.reset_index(drop=False)

# Print the resulting DataFrame
print(financial_data4_df)

                          Date  S&P 500 Daily Performance  \
0    2019-08-29 00:00:00-04:00                   0.488253
1    2019-08-30 00:00:00-04:00                  -0.361927
2    2019-08-31 00:00:00-04:00                        NaN
3    2019-09-01 00:00:00-04:00                        NaN
4    2019-09-02 00:00:00-04:00                        NaN
...                        ...                        ...
1282 2023-03-03 00:00:00-05:00                   1.191086
1283 2023-03-04 00:00:00-05:00                        NaN
1284 2023-03-05 00:00:00-05:00                        NaN
1285 2023-03-06 00:00:00-05:00                  -0.165961
1286 2023-03-07 00:00:00-05:00                  -1.528802

      NASDAQ 100 Daily Performance  1-Year Treasury Bond Rate  \
0                         0.307606                      1.940
1                        -0.674524                      1.933
2                              NaN                      1.933
3                              NaN                      1.933
4                              NaN                      1.933
...                            ...                        ...
1282                      1.487110                      4.718
1283                           NaN                      4.718
1284                           NaN                      4.718
1285                     -0.341605                      4.728
1286                     -1.227491                      4.845

      5-Year Treasury Bond Rate  10-Year Treasury Bond Rate  \
0                         1.516                       1.516
1                         1.506                       1.506
2                         1.506                       1.506
3                         1.506                       1.506
4                         1.506                       1.506
...                         ...                         ...
1282                      3.964                       3.964
1283                      3.964                       3.964
1284                      3.964                       3.964
1285                      3.983                       3.983
1286                      3.975                       3.975

      30-Year Treasury Bond Rate  Bitcoin Futures Volume  \
0                          1.516                  4154.0
1                          1.506                  2856.0
2                          1.506                     NaN
3                          1.506                     NaN
4                          1.506                     NaN
...                          ...                     ...
1282                       3.964                 12038.0
1283                       3.964                     NaN
1284                       3.964                     NaN
1285                       3.983                  4800.0
1286                       3.975                  6742.0

      Bitcoin Futures Returns  Bitcoin Futures Volatility
0                   -1.959773                    3.918991
1                    0.883789                    3.918991
2                         NaN                    3.918991
3                         NaN                    3.918991
4                         NaN                    3.918991
...                       ...                         ...
1282                -5.263158                    3.918991
1283                      NaN                    3.918991
1284                      NaN                    3.918991
1285                -0.289468                    3.918991
1286                -1.714540                    3.918991

[1287 rows x 10 columns]

In [152]:
financial_data4_df

,Date,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns,Bitcoin Futures Volatility
0,2019-08-29 00:00:00-04:00,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773,3.918991
1,2019-08-30 00:00:00-04:00,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789,3.918991
2,2019-08-31 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN,3.918991
3,2019-09-01 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN,3.918991
4,2019-09-02 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN,3.918991
...,...,...,...,...,...,...,...,...,...,...
1282,2023-03-03 00:00:00-05:00,1.191086,1.487110,4.718,3.964,3.964,3.964,12038.0,-5.263158,3.918991
1283,2023-03-04 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN,3.918991
1284,2023-03-05 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN,3.918991
1285,2023-03-06 00:00:00-05:00,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468,3.918991
1286,2023-03-07 00:00:00-05:00,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540,3.918991

In [154]:
financial_data4_df.drop(columns=['Bitcoin Futures Volatility'], inplace=True)

In [156]:
financial_data4_df

,Date,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29 00:00:00-04:00,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30 00:00:00-04:00,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1282,2023-03-03 00:00:00-05:00,1.191086,1.487110,4.718,3.964,3.964,3.964,12038.0,-5.263158
1283,2023-03-04 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06 00:00:00-05:00,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07 00:00:00-05:00,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540

In [104]:
# # Reset the index of merged_df
# merged_df = merged_df.reset_index(drop=False)

# # Print the resulting DataFrame
# print(merged_df)

           date        time          open         close          high  \
0    2019-08-29  1567036800   9756.785707   9510.200544   9756.785707
1    2019-08-30  1567123200   9514.844852   9598.173648   9656.123926
2    2019-08-31  1567209600   9597.539448   9630.663848   9673.220440
3    2019-09-01  1567296000   9630.593196   9757.970318   9796.755968
4    2019-09-02  1567382400   9757.473237  10346.760793  10396.591325
...         ...         ...           ...           ...           ...
1283 2023-03-04  1677888000  22362.923027  22353.350074  22405.176954
1284 2023-03-05  1677974400  22354.143598  22435.514197  22613.685231
1285 2023-03-06  1678060800  22436.816776  22429.757533  22584.293809
1286 2023-03-07  1678147200  22428.322390  22219.769071  22527.418642
1287 2023-03-08  1678233600  22216.442321  21718.079830  22268.896252

               low        volume    volume_24h    market_cap  \
0      9421.630160  1.544143e+10  1.704588e+10  1.702749e+11
1      9428.302397  1.208824e+10  1.359526e+10  1.718692e+11
2      9531.799839  9.854216e+09  1.145481e+10  1.724707e+11
3      9582.944631  9.730741e+09  1.144536e+10  1.747683e+11
4      9730.650717  1.499891e+10  1.724810e+10  1.853331e+11
...            ...           ...           ...           ...
1283  22198.981009           NaN  1.116601e+10  4.316073e+11
1284  22307.143313           NaN  1.331700e+10  4.332162e+11
1285  22331.314828           NaN  1.735319e+10  4.331225e+11
1286  22011.262497           NaN  2.276545e+10  4.290907e+11
1287  21708.050506           NaN  2.253658e+10  4.194214e+11

      circulating_supply  url_shares  unique_url_shares  reddit_posts  \
0               17902412        80.0               80.0         240.0
1               17904475        68.0               68.0         211.0
2               17906475        56.0               56.0         158.0
3               17908500        56.0               56.0         150.0
4               17910337        87.0               87.0         206.0
...                  ...         ...                ...           ...
1283            19308443     52255.0             4509.0         847.0
1284            19309437     41091.0             4141.0         716.0
1285            19310231     54697.0             6679.0        1105.0
1286            19311281     59540.0             6450.0         941.0
1287            19312112     55377.0             6215.0         983.0

      reddit_posts_score  reddit_comments  reddit_comments_score    tweets  \
0                 6980.0           1032.0                 4684.0   35865.0
1                 6366.0           1020.0                 4781.0   33808.0
2                 4306.0            828.0                 3623.0   28603.0
3                 5465.0            742.0                 3347.0   31736.0
4                 6785.0           1066.0                 5620.0   37310.0
...                  ...              ...                    ...       ...
1283              3405.0           2308.0                 5591.0  267079.0
1284              6987.0           2513.0                 6434.0  268189.0
1285              4810.0           2847.0                10706.0  359141.0
1286              3944.0           2651.0                 7502.0  344943.0
1287              4585.0           3651.0                 8470.0  267005.0

      tweet_spam  tweet_followers  tweet_quotes  tweet_retweets  \
0         3580.0              NaN           NaN             NaN
1         3350.0              NaN           NaN             NaN
2         3551.0              NaN           NaN             NaN
3         3664.0              NaN           NaN             NaN
4         4161.0              NaN           NaN             NaN
...          ...              ...           ...             ...
1283    155619.0     9.264580e+08        3878.0         64823.0
1284    174436.0     8.751753e+08       21741.0         59450.0
1285    222373.0     1.197015e+09       13853.0         90663.0
1286    180947.0     1.374308e+09        4797.0         79405.0
1287    207452.0     1.131440e+09        4434.0         71128.0

      tweet_replies  tweet_favorites  tweet_sentiment1  tweet_sentiment2  \
0               NaN              NaN            1603.0            3430.0
1               NaN              NaN            1501.0            3083.0
2               NaN              NaN            1147.0            2165.0
3               NaN              NaN            1176.0            2528.0
4               NaN              NaN            1742.0            3207.0
...             ...              ...               ...               ...
1283        36844.0         206599.0             498.0            9913.0
1284        36262.0         224585.0             450.0            9059.0
1285        48067.0         300224.0             510.0           11580.0
1286        46217.0         261429.0             507.0           11814.0
1287        42789.0         253187.0             777.0           10301.0

      tweet_sentiment3  tweet_sentiment4  tweet_sentiment5  \
0               6559.0           18886.0            1807.0
1               6082.0           18090.0            1702.0
2               5504.0           14760.0            1476.0
3               5694.0           17046.0            1628.0
4               6477.0           19967.0            1756.0
...                ...               ...               ...
1283          120831.0          133465.0            2372.0
1284          124496.0          131222.0            2962.0
1285          150406.0          193006.0            3638.0
1286          137035.0          192830.0            2757.0
1287           93111.0          160587.0            2229.0

      tweet_sentiment_impact1  tweet_sentiment_impact2  \
0                   8651361.0               22634384.0
1                  23926344.0               28730015.0
2                  33382004.0               38082040.0
3                   9017973.0               20622075.0
4                  35499592.0               28099972.0
...                       ...                      ...
1283                7304761.0               81552672.0
1284                2287570.0               57981678.0
1285                8728612.0               73404851.0
1286               10545582.0               72733817.0
1287                3439410.0              100168088.0

      tweet_sentiment_impact3  tweet_sentiment_impact4  \
0                  49073801.0              136696642.0
1                  41017312.0              127370516.0
2                  31465126.0              100024109.0
3                  32667021.0              126860768.0
4                  42822372.0              140741661.0
...                       ...                      ...
1283              307309761.0              520593633.0
1284              329460461.0              476534730.0
1285              440109724.0              657819860.0
1286              592071450.0              681497291.0
1287              333766714.0              687105359.0

      tweet_sentiment_impact5  social_score  average_sentiment  \
0                  12868795.0  2.299354e+08                3.5
1                  11893234.0  2.329465e+08                3.5
2                   7893289.0  2.108529e+08                3.5
3                   8962276.0  1.981383e+08                3.5
4                  12325373.0  2.595008e+08                3.5
...                       ...           ...                ...
1283               10009332.0  9.268314e+08                3.5
1284                9252924.0  8.755719e+08                3.5
1285               17404481.0  1.197538e+09                3.5
1286               17851746.0  1.374771e+09                3.5
1287                7331637.0  1.131880e+09                3.6

      sentiment_absolute  sentiment_relative  search_average   news  \
0                    NaN                 NaN            52.0  330.0
1                    NaN                 NaN            50.0  316.0
2                    NaN                 NaN            43.0  170.0
3                    NaN                 NaN            40.0    7.0
4                    NaN                 NaN            50.0  267.0
...                  ...                 ...             ...    ...
1283                 3.0                93.0             NaN  155.0
1284                 3.0                93.0             NaN  127.0
1285                 3.0                94.0             NaN  297.0
1286                 3.0                94.0             NaN  335.0
1287                 3.0                94.0             NaN  312.0

      price_score  social_impact_score  correlation_rank  galaxy_score  \
0             1.0                  4.0               4.0          62.5
1             5.0                  4.0               4.0          82.5
2             4.2                  4.0               4.0          78.5
3             3.7                  2.0               4.0          66.0
4             1.4                  2.0               4.0          54.5
...           ...                  ...               ...           ...
1283          1.0                  3.0               1.0          42.4
1284          1.0                  3.0               1.0          42.4
1285          1.0                  3.0               1.0          42.6
1286          1.0                  3.0               1.0          42.7
1287          1.0                  3.0               1.0          43.0

      volatility  alt_rank  alt_rank_30d  alt_rank_hour_average  \
0       0.624617       NaN           NaN                    NaN
1       0.529363       NaN           NaN                    NaN
2       0.151796       NaN           NaN                    NaN
3       0.090203       NaN           NaN                    NaN
4       0.257690       NaN           NaN                    NaN
...          ...       ...           ...                    ...
1283    0.020725     137.0          22.0                 261.83
1284    0.014853      14.0          64.0                  46.33
1285    0.002277      40.0          25.0                 109.25
1286    0.003805      65.0          60.0                 158.58
1287    0.007676      58.0          44.0                 142.25

      market_cap_rank  percent_change_24h_rank  volume_24h_rank  \
0                 NaN                      NaN              NaN
1                 NaN                      NaN              NaN
2                 NaN                      NaN              NaN
3                 NaN                      NaN              NaN
4                 NaN                      NaN              NaN
...               ...                      ...              ...
1283              1.0                   2794.0              2.0
1284              1.0                    803.0              2.0
1285              1.0                   3118.0              2.0
1286              1.0                   3154.0              2.0
1287              1.0                   3214.0              2.0

      social_volume_24h_rank  social_score_24h_rank  medium  youtube  \
0                        NaN                    NaN     NaN      NaN
1                        NaN                    NaN     NaN      NaN
2                        NaN                    NaN     NaN      NaN
3                        NaN                    NaN     NaN      NaN
4                        NaN                    NaN     NaN      NaN
...                      ...                    ...     ...      ...
1283                     2.0                    1.0    19.0    382.0
1284                     1.0                    1.0     5.0    371.0
1285                     2.0                    1.0     9.0    469.0
1286                     1.0                    1.0    12.0    474.0
1287                     2.0                    1.0     5.0    481.0

      social_contributors  influential_content  influential_content_score  \
0                 14178.0                  NaN                        NaN
1                 12955.0                  NaN                        NaN
2                 11277.0                  NaN                        NaN
3                  9597.0                  NaN                        NaN
4                 11568.0                  NaN                        NaN
...                   ...                  ...                        ...
1283             155477.0                809.0                   629808.0
1284             162513.0                888.0                   702934.0
1285             231981.0               1359.0                  1115135.0
1286             207784.0               1318.0                  1062812.0
1287             186460.0               1240.0                   973915.0

            sma_50       sma_100       sma_200  social_volume  \
0     10524.912498  10072.925364   7489.222465        37547.0
1     10489.702736  10092.106435   7518.971180        35423.0
2     10445.996280  10109.594606   7548.856856        29815.0
3     10413.308099  10127.300594   7579.486355        32691.0
4     10415.122150  10150.242763   7613.135754        38936.0
...            ...           ...           ...            ...
1283  22921.778114  19968.458775  19725.154453       274898.0
1284  22950.962403  20027.595507  19720.652033       275686.0
1285  22981.941569  20087.250271  19716.737125       370069.0
1286  23002.944295  20145.001693  19723.448202       355320.0
1287  23014.075507  20200.009267  19726.208299       278166.0

      market_cap_global  market_dominance  social_volume_global  \
0          2.455443e+11         69.345902              111697.0
1          2.486567e+11         69.119069              108047.0
2          2.488274e+11         69.313417               87587.0
3          2.511694e+11         69.581853               91851.0
4          2.642592e+11         70.133082              105847.0
...                 ...               ...                   ...
1283       1.028053e+12         41.982981             2630450.0
1284       1.022768e+12         42.357236             2241463.0
1285       1.024951e+12         42.257871             2278351.0
1286       1.024529e+12         41.881735             2244864.0
1287       1.017419e+12         41.224072             2224407.0

      social_dominance  Day of Month  month  Daily % Change
0            33.615048            29      8             NaN
1            32.784807            30      8        0.925039
2            34.040440            31      8        0.338504
3            35.591338             1      9        1.321887
4            36.785171             2      9        6.033944
...                ...           ...    ...             ...
1283         10.450607             4      3       -0.041718
1284         12.299378             5      3        0.367570
1285         16.242844             6      3       -0.025659
1286         15.828130             7      3       -0.936205
1287         12.505176             8      3       -2.257851

[1288 rows x 68 columns]

In [157]:
merged_df

,time,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_followers,tweet_quotes,tweet_retweets,tweet_replies,tweet_favorites,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,sentiment_absolute,sentiment_relative,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,alt_rank,alt_rank_30d,alt_rank_hour_average,market_cap_rank,percent_change_24h_rank,volume_24h_rank,social_volume_24h_rank,social_score_24h_rank,medium,youtube,social_contributors,influential_content,influential_content_score,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2019-08-29,1567036800,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,NaN,NaN,NaN,NaN,NaN,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,NaN,NaN,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14178.0,NaN,NaN,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN
2019-08-30,1567123200,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,NaN,NaN,NaN,NaN,NaN,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,NaN,NaN,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12955.0,NaN,NaN,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039
2019-08-31,1567209600,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,NaN,NaN,NaN,NaN,NaN,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,NaN,NaN,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11277.0,NaN,NaN,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504
2019-09-01,1567296000,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,NaN,NaN,NaN,NaN,NaN,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,NaN,NaN,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9597.0,NaN,NaN,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887
2019-09-02,1567382400,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,NaN,NaN,NaN,NaN,NaN,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,NaN,NaN,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11568.0,NaN,NaN,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-04,1677888000,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,9.264580e+08,3878.0,64823.0,36844.0,206599.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,3.0,93.0,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,137.0,22.0,261.83,1.0,2794.0,2.0,2.0,1.0,19.0,382.0,155477.0,809.0,629808.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718
2023-03-05,1677974400,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,8.751753e+08,21741.0,59450.0,36262.0,224585.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,3.0,93.0,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,14.0,64.0,46.33,1.0,803.0,2.0,1.0,1.0,5.0,371.0,162513.0,888.0,702934.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570
2023-03-06,1678060800,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,1.197015e+09,13853.0,90663.0,48067.0,300224.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,3.0,94.0,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,40.0,25.0,109.25,1.0,3118.0,2.0,2.0,1.0,9.0,469.0,231981.0,1359.0,1115135.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659
2023-03-07,1678147200,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,1.374308e+09,4797.0,79405.0,46217.0,261429.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,3.0,94.0,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,65.0,60.0,158.58,1.0,3154.0,2.0,1.0,1.0,12.0,474.0,207784.0,1318.0,1062812.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205
2023-03-08,1678233600,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,1.131440e+09,4434.0,71128.0,42789.0,253187.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,3.0,94.0,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,58.0,44.0,142.25,1.0,3214.0,2.0,2.0,1.0,5.0,481.0,186460.0,1240.0,973915.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851

In [158]:
# Reset the index of merged_df
merged_df = merged_df.reset_index(drop=False)

# Print the resulting DataFrame
print(merged_df)

           date        time          open         close          high  \
0    2019-08-29  1567036800   9756.785707   9510.200544   9756.785707
1    2019-08-30  1567123200   9514.844852   9598.173648   9656.123926
2    2019-08-31  1567209600   9597.539448   9630.663848   9673.220440
3    2019-09-01  1567296000   9630.593196   9757.970318   9796.755968
4    2019-09-02  1567382400   9757.473237  10346.760793  10396.591325
...         ...         ...           ...           ...           ...
1283 2023-03-04  1677888000  22362.923027  22353.350074  22405.176954
1284 2023-03-05  1677974400  22354.143598  22435.514197  22613.685231
1285 2023-03-06  1678060800  22436.816776  22429.757533  22584.293809
1286 2023-03-07  1678147200  22428.322390  22219.769071  22527.418642
1287 2023-03-08  1678233600  22216.442321  21718.079830  22268.896252

               low        volume    volume_24h    market_cap  \
0      9421.630160  1.544143e+10  1.704588e+10  1.702749e+11
1      9428.302397  1.208824e+10  1.359526e+10  1.718692e+11
2      9531.799839  9.854216e+09  1.145481e+10  1.724707e+11
3      9582.944631  9.730741e+09  1.144536e+10  1.747683e+11
4      9730.650717  1.499891e+10  1.724810e+10  1.853331e+11
...            ...           ...           ...           ...
1283  22198.981009           NaN  1.116601e+10  4.316073e+11
1284  22307.143313           NaN  1.331700e+10  4.332162e+11
1285  22331.314828           NaN  1.735319e+10  4.331225e+11
1286  22011.262497           NaN  2.276545e+10  4.290907e+11
1287  21708.050506           NaN  2.253658e+10  4.194214e+11

      circulating_supply  url_shares  unique_url_shares  reddit_posts  \
0               17902412        80.0               80.0         240.0
1               17904475        68.0               68.0         211.0
2               17906475        56.0               56.0         158.0
3               17908500        56.0               56.0         150.0
4               17910337        87.0               87.0         206.0
...                  ...         ...                ...           ...
1283            19308443     52255.0             4509.0         847.0
1284            19309437     41091.0             4141.0         716.0
1285            19310231     54697.0             6679.0        1105.0
1286            19311281     59540.0             6450.0         941.0
1287            19312112     55377.0             6215.0         983.0

      reddit_posts_score  reddit_comments  reddit_comments_score    tweets  \
0                 6980.0           1032.0                 4684.0   35865.0
1                 6366.0           1020.0                 4781.0   33808.0
2                 4306.0            828.0                 3623.0   28603.0
3                 5465.0            742.0                 3347.0   31736.0
4                 6785.0           1066.0                 5620.0   37310.0
...                  ...              ...                    ...       ...
1283              3405.0           2308.0                 5591.0  267079.0
1284              6987.0           2513.0                 6434.0  268189.0
1285              4810.0           2847.0                10706.0  359141.0
1286              3944.0           2651.0                 7502.0  344943.0
1287              4585.0           3651.0                 8470.0  267005.0

      tweet_spam  tweet_followers  tweet_quotes  tweet_retweets  \
0         3580.0              NaN           NaN             NaN
1         3350.0              NaN           NaN             NaN
2         3551.0              NaN           NaN             NaN
3         3664.0              NaN           NaN             NaN
4         4161.0              NaN           NaN             NaN
...          ...              ...           ...             ...
1283    155619.0     9.264580e+08        3878.0         64823.0
1284    174436.0     8.751753e+08       21741.0         59450.0
1285    222373.0     1.197015e+09       13853.0         90663.0
1286    180947.0     1.374308e+09        4797.0         79405.0
1287    207452.0     1.131440e+09        4434.0         71128.0

      tweet_replies  tweet_favorites  tweet_sentiment1  tweet_sentiment2  \
0               NaN              NaN            1603.0            3430.0
1               NaN              NaN            1501.0            3083.0
2               NaN              NaN            1147.0            2165.0
3               NaN              NaN            1176.0            2528.0
4               NaN              NaN            1742.0            3207.0
...             ...              ...               ...               ...
1283        36844.0         206599.0             498.0            9913.0
1284        36262.0         224585.0             450.0            9059.0
1285        48067.0         300224.0             510.0           11580.0
1286        46217.0         261429.0             507.0           11814.0
1287        42789.0         253187.0             777.0           10301.0

      tweet_sentiment3  tweet_sentiment4  tweet_sentiment5  \
0               6559.0           18886.0            1807.0
1               6082.0           18090.0            1702.0
2               5504.0           14760.0            1476.0
3               5694.0           17046.0            1628.0
4               6477.0           19967.0            1756.0
...                ...               ...               ...
1283          120831.0          133465.0            2372.0
1284          124496.0          131222.0            2962.0
1285          150406.0          193006.0            3638.0
1286          137035.0          192830.0            2757.0
1287           93111.0          160587.0            2229.0

      tweet_sentiment_impact1  tweet_sentiment_impact2  \
0                   8651361.0               22634384.0
1                  23926344.0               28730015.0
2                  33382004.0               38082040.0
3                   9017973.0               20622075.0
4                  35499592.0               28099972.0
...                       ...                      ...
1283                7304761.0               81552672.0
1284                2287570.0               57981678.0
1285                8728612.0               73404851.0
1286               10545582.0               72733817.0
1287                3439410.0              100168088.0

      tweet_sentiment_impact3  tweet_sentiment_impact4  \
0                  49073801.0              136696642.0
1                  41017312.0              127370516.0
2                  31465126.0              100024109.0
3                  32667021.0              126860768.0
4                  42822372.0              140741661.0
...                       ...                      ...
1283              307309761.0              520593633.0
1284              329460461.0              476534730.0
1285              440109724.0              657819860.0
1286              592071450.0              681497291.0
1287              333766714.0              687105359.0

      tweet_sentiment_impact5  social_score  average_sentiment  \
0                  12868795.0  2.299354e+08                3.5
1                  11893234.0  2.329465e+08                3.5
2                   7893289.0  2.108529e+08                3.5
3                   8962276.0  1.981383e+08                3.5
4                  12325373.0  2.595008e+08                3.5
...                       ...           ...                ...
1283               10009332.0  9.268314e+08                3.5
1284                9252924.0  8.755719e+08                3.5
1285               17404481.0  1.197538e+09                3.5
1286               17851746.0  1.374771e+09                3.5
1287                7331637.0  1.131880e+09                3.6

      sentiment_absolute  sentiment_relative  search_average   news  \
0                    NaN                 NaN            52.0  330.0
1                    NaN                 NaN            50.0  316.0
2                    NaN                 NaN            43.0  170.0
3                    NaN                 NaN            40.0    7.0
4                    NaN                 NaN            50.0  267.0
...                  ...                 ...             ...    ...
1283                 3.0                93.0             NaN  155.0
1284                 3.0                93.0             NaN  127.0
1285                 3.0                94.0             NaN  297.0
1286                 3.0                94.0             NaN  335.0
1287                 3.0                94.0             NaN  312.0

      price_score  social_impact_score  correlation_rank  galaxy_score  \
0             1.0                  4.0               4.0          62.5
1             5.0                  4.0               4.0          82.5
2             4.2                  4.0               4.0          78.5
3             3.7                  2.0               4.0          66.0
4             1.4                  2.0               4.0          54.5
...           ...                  ...               ...           ...
1283          1.0                  3.0               1.0          42.4
1284          1.0                  3.0               1.0          42.4
1285          1.0                  3.0               1.0          42.6
1286          1.0                  3.0               1.0          42.7
1287          1.0                  3.0               1.0          43.0

      volatility  alt_rank  alt_rank_30d  alt_rank_hour_average  \
0       0.624617       NaN           NaN                    NaN
1       0.529363       NaN           NaN                    NaN
2       0.151796       NaN           NaN                    NaN
3       0.090203       NaN           NaN                    NaN
4       0.257690       NaN           NaN                    NaN
...          ...       ...           ...                    ...
1283    0.020725     137.0          22.0                 261.83
1284    0.014853      14.0          64.0                  46.33
1285    0.002277      40.0          25.0                 109.25
1286    0.003805      65.0          60.0                 158.58
1287    0.007676      58.0          44.0                 142.25

      market_cap_rank  percent_change_24h_rank  volume_24h_rank  \
0                 NaN                      NaN              NaN
1                 NaN                      NaN              NaN
2                 NaN                      NaN              NaN
3                 NaN                      NaN              NaN
4                 NaN                      NaN              NaN
...               ...                      ...              ...
1283              1.0                   2794.0              2.0
1284              1.0                    803.0              2.0
1285              1.0                   3118.0              2.0
1286              1.0                   3154.0              2.0
1287              1.0                   3214.0              2.0

      social_volume_24h_rank  social_score_24h_rank  medium  youtube  \
0                        NaN                    NaN     NaN      NaN
1                        NaN                    NaN     NaN      NaN
2                        NaN                    NaN     NaN      NaN
3                        NaN                    NaN     NaN      NaN
4                        NaN                    NaN     NaN      NaN
...                      ...                    ...     ...      ...
1283                     2.0                    1.0    19.0    382.0
1284                     1.0                    1.0     5.0    371.0
1285                     2.0                    1.0     9.0    469.0
1286                     1.0                    1.0    12.0    474.0
1287                     2.0                    1.0     5.0    481.0

      social_contributors  influential_content  influential_content_score  \
0                 14178.0                  NaN                        NaN
1                 12955.0                  NaN                        NaN
2                 11277.0                  NaN                        NaN
3                  9597.0                  NaN                        NaN
4                 11568.0                  NaN                        NaN
...                   ...                  ...                        ...
1283             155477.0                809.0                   629808.0
1284             162513.0                888.0                   702934.0
1285             231981.0               1359.0                  1115135.0
1286             207784.0               1318.0                  1062812.0
1287             186460.0               1240.0                   973915.0

            sma_50       sma_100       sma_200  social_volume  \
0     10524.912498  10072.925364   7489.222465        37547.0
1     10489.702736  10092.106435   7518.971180        35423.0
2     10445.996280  10109.594606   7548.856856        29815.0
3     10413.308099  10127.300594   7579.486355        32691.0
4     10415.122150  10150.242763   7613.135754        38936.0
...            ...           ...           ...            ...
1283  22921.778114  19968.458775  19725.154453       274898.0
1284  22950.962403  20027.595507  19720.652033       275686.0
1285  22981.941569  20087.250271  19716.737125       370069.0
1286  23002.944295  20145.001693  19723.448202       355320.0
1287  23014.075507  20200.009267  19726.208299       278166.0

      market_cap_global  market_dominance  social_volume_global  \
0          2.455443e+11         69.345902              111697.0
1          2.486567e+11         69.119069              108047.0
2          2.488274e+11         69.313417               87587.0
3          2.511694e+11         69.581853               91851.0
4          2.642592e+11         70.133082              105847.0
...                 ...               ...                   ...
1283       1.028053e+12         41.982981             2630450.0
1284       1.022768e+12         42.357236             2241463.0
1285       1.024951e+12         42.257871             2278351.0
1286       1.024529e+12         41.881735             2244864.0
1287       1.017419e+12         41.224072             2224407.0

      social_dominance  Day of Month  month  Daily % Change
0            33.615048            29      8             NaN
1            32.784807            30      8        0.925039
2            34.040440            31      8        0.338504
3            35.591338             1      9        1.321887
4            36.785171             2      9        6.033944
...                ...           ...    ...             ...
1283         10.450607             4      3       -0.041718
1284         12.299378             5      3        0.367570
1285         16.242844             6      3       -0.025659
1286         15.828130             7      3       -0.936205
1287         12.505176             8      3       -2.257851

[1288 rows x 68 columns]

In [159]:
# Merge merged_df and financial_data4_df on their indices
merged_df = merged_df.merge(financial_data4_df, how='outer', left_index=True, right_index=True)

# Print the resulting DataFrame
print(merged_df)

           date        time          open         close          high  \
0    2019-08-29  1567036800   9756.785707   9510.200544   9756.785707
1    2019-08-30  1567123200   9514.844852   9598.173648   9656.123926
2    2019-08-31  1567209600   9597.539448   9630.663848   9673.220440
3    2019-09-01  1567296000   9630.593196   9757.970318   9796.755968
4    2019-09-02  1567382400   9757.473237  10346.760793  10396.591325
...         ...         ...           ...           ...           ...
1283 2023-03-04  1677888000  22362.923027  22353.350074  22405.176954
1284 2023-03-05  1677974400  22354.143598  22435.514197  22613.685231
1285 2023-03-06  1678060800  22436.816776  22429.757533  22584.293809
1286 2023-03-07  1678147200  22428.322390  22219.769071  22527.418642
1287 2023-03-08  1678233600  22216.442321  21718.079830  22268.896252

               low        volume    volume_24h    market_cap  \
0      9421.630160  1.544143e+10  1.704588e+10  1.702749e+11
1      9428.302397  1.208824e+10  1.359526e+10  1.718692e+11
2      9531.799839  9.854216e+09  1.145481e+10  1.724707e+11
3      9582.944631  9.730741e+09  1.144536e+10  1.747683e+11
4      9730.650717  1.499891e+10  1.724810e+10  1.853331e+11
...            ...           ...           ...           ...
1283  22198.981009           NaN  1.116601e+10  4.316073e+11
1284  22307.143313           NaN  1.331700e+10  4.332162e+11
1285  22331.314828           NaN  1.735319e+10  4.331225e+11
1286  22011.262497           NaN  2.276545e+10  4.290907e+11
1287  21708.050506           NaN  2.253658e+10  4.194214e+11

      circulating_supply  url_shares  unique_url_shares  reddit_posts  \
0               17902412        80.0               80.0         240.0
1               17904475        68.0               68.0         211.0
2               17906475        56.0               56.0         158.0
3               17908500        56.0               56.0         150.0
4               17910337        87.0               87.0         206.0
...                  ...         ...                ...           ...
1283            19308443     52255.0             4509.0         847.0
1284            19309437     41091.0             4141.0         716.0
1285            19310231     54697.0             6679.0        1105.0
1286            19311281     59540.0             6450.0         941.0
1287            19312112     55377.0             6215.0         983.0

      reddit_posts_score  reddit_comments  reddit_comments_score    tweets  \
0                 6980.0           1032.0                 4684.0   35865.0
1                 6366.0           1020.0                 4781.0   33808.0
2                 4306.0            828.0                 3623.0   28603.0
3                 5465.0            742.0                 3347.0   31736.0
4                 6785.0           1066.0                 5620.0   37310.0
...                  ...              ...                    ...       ...
1283              3405.0           2308.0                 5591.0  267079.0
1284              6987.0           2513.0                 6434.0  268189.0
1285              4810.0           2847.0                10706.0  359141.0
1286              3944.0           2651.0                 7502.0  344943.0
1287              4585.0           3651.0                 8470.0  267005.0

      tweet_spam  tweet_followers  tweet_quotes  tweet_retweets  \
0         3580.0              NaN           NaN             NaN
1         3350.0              NaN           NaN             NaN
2         3551.0              NaN           NaN             NaN
3         3664.0              NaN           NaN             NaN
4         4161.0              NaN           NaN             NaN
...          ...              ...           ...             ...
1283    155619.0     9.264580e+08        3878.0         64823.0
1284    174436.0     8.751753e+08       21741.0         59450.0
1285    222373.0     1.197015e+09       13853.0         90663.0
1286    180947.0     1.374308e+09        4797.0         79405.0
1287    207452.0     1.131440e+09        4434.0         71128.0

      tweet_replies  tweet_favorites  tweet_sentiment1  tweet_sentiment2  \
0               NaN              NaN            1603.0            3430.0
1               NaN              NaN            1501.0            3083.0
2               NaN              NaN            1147.0            2165.0
3               NaN              NaN            1176.0            2528.0
4               NaN              NaN            1742.0            3207.0
...             ...              ...               ...               ...
1283        36844.0         206599.0             498.0            9913.0
1284        36262.0         224585.0             450.0            9059.0
1285        48067.0         300224.0             510.0           11580.0
1286        46217.0         261429.0             507.0           11814.0
1287        42789.0         253187.0             777.0           10301.0

      tweet_sentiment3  tweet_sentiment4  tweet_sentiment5  \
0               6559.0           18886.0            1807.0
1               6082.0           18090.0            1702.0
2               5504.0           14760.0            1476.0
3               5694.0           17046.0            1628.0
4               6477.0           19967.0            1756.0
...                ...               ...               ...
1283          120831.0          133465.0            2372.0
1284          124496.0          131222.0            2962.0
1285          150406.0          193006.0            3638.0
1286          137035.0          192830.0            2757.0
1287           93111.0          160587.0            2229.0

      tweet_sentiment_impact1  tweet_sentiment_impact2  \
0                   8651361.0               22634384.0
1                  23926344.0               28730015.0
2                  33382004.0               38082040.0
3                   9017973.0               20622075.0
4                  35499592.0               28099972.0
...                       ...                      ...
1283                7304761.0               81552672.0
1284                2287570.0               57981678.0
1285                8728612.0               73404851.0
1286               10545582.0               72733817.0
1287                3439410.0              100168088.0

      tweet_sentiment_impact3  tweet_sentiment_impact4  \
0                  49073801.0              136696642.0
1                  41017312.0              127370516.0
2                  31465126.0              100024109.0
3                  32667021.0              126860768.0
4                  42822372.0              140741661.0
...                       ...                      ...
1283              307309761.0              520593633.0
1284              329460461.0              476534730.0
1285              440109724.0              657819860.0
1286              592071450.0              681497291.0
1287              333766714.0              687105359.0

      tweet_sentiment_impact5  social_score  average_sentiment  \
0                  12868795.0  2.299354e+08                3.5
1                  11893234.0  2.329465e+08                3.5
2                   7893289.0  2.108529e+08                3.5
3                   8962276.0  1.981383e+08                3.5
4                  12325373.0  2.595008e+08                3.5
...                       ...           ...                ...
1283               10009332.0  9.268314e+08                3.5
1284                9252924.0  8.755719e+08                3.5
1285               17404481.0  1.197538e+09                3.5
1286               17851746.0  1.374771e+09                3.5
1287                7331637.0  1.131880e+09                3.6

      sentiment_absolute  sentiment_relative  search_average   news  \
0                    NaN                 NaN            52.0  330.0
1                    NaN                 NaN            50.0  316.0
2                    NaN                 NaN            43.0  170.0
3                    NaN                 NaN            40.0    7.0
4                    NaN                 NaN            50.0  267.0
...                  ...                 ...             ...    ...
1283                 3.0                93.0             NaN  155.0
1284                 3.0                93.0             NaN  127.0
1285                 3.0                94.0             NaN  297.0
1286                 3.0                94.0             NaN  335.0
1287                 3.0                94.0             NaN  312.0

      price_score  social_impact_score  correlation_rank  galaxy_score  \
0             1.0                  4.0               4.0          62.5
1             5.0                  4.0               4.0          82.5
2             4.2                  4.0               4.0          78.5
3             3.7                  2.0               4.0          66.0
4             1.4                  2.0               4.0          54.5
...           ...                  ...               ...           ...
1283          1.0                  3.0               1.0          42.4
1284          1.0                  3.0               1.0          42.4
1285          1.0                  3.0               1.0          42.6
1286          1.0                  3.0               1.0          42.7
1287          1.0                  3.0               1.0          43.0

      volatility  alt_rank  alt_rank_30d  alt_rank_hour_average  \
0       0.624617       NaN           NaN                    NaN
1       0.529363       NaN           NaN                    NaN
2       0.151796       NaN           NaN                    NaN
3       0.090203       NaN           NaN                    NaN
4       0.257690       NaN           NaN                    NaN
...          ...       ...           ...                    ...
1283    0.020725     137.0          22.0                 261.83
1284    0.014853      14.0          64.0                  46.33
1285    0.002277      40.0          25.0                 109.25
1286    0.003805      65.0          60.0                 158.58
1287    0.007676      58.0          44.0                 142.25

      market_cap_rank  percent_change_24h_rank  volume_24h_rank  \
0                 NaN                      NaN              NaN
1                 NaN                      NaN              NaN
2                 NaN                      NaN              NaN
3                 NaN                      NaN              NaN
4                 NaN                      NaN              NaN
...               ...                      ...              ...
1283              1.0                   2794.0              2.0
1284              1.0                    803.0              2.0
1285              1.0                   3118.0              2.0
1286              1.0                   3154.0              2.0
1287              1.0                   3214.0              2.0

      social_volume_24h_rank  social_score_24h_rank  medium  youtube  \
0                        NaN                    NaN     NaN      NaN
1                        NaN                    NaN     NaN      NaN
2                        NaN                    NaN     NaN      NaN
3                        NaN                    NaN     NaN      NaN
4                        NaN                    NaN     NaN      NaN
...                      ...                    ...     ...      ...
1283                     2.0                    1.0    19.0    382.0
1284                     1.0                    1.0     5.0    371.0
1285                     2.0                    1.0     9.0    469.0
1286                     1.0                    1.0    12.0    474.0
1287                     2.0                    1.0     5.0    481.0

      social_contributors  influential_content  influential_content_score  \
0                 14178.0                  NaN                        NaN
1                 12955.0                  NaN                        NaN
2                 11277.0                  NaN                        NaN
3                  9597.0                  NaN                        NaN
4                 11568.0                  NaN                        NaN
...                   ...                  ...                        ...
1283             155477.0                809.0                   629808.0
1284             162513.0                888.0                   702934.0
1285             231981.0               1359.0                  1115135.0
1286             207784.0               1318.0                  1062812.0
1287             186460.0               1240.0                   973915.0

            sma_50       sma_100       sma_200  social_volume  \
0     10524.912498  10072.925364   7489.222465        37547.0
1     10489.702736  10092.106435   7518.971180        35423.0
2     10445.996280  10109.594606   7548.856856        29815.0
3     10413.308099  10127.300594   7579.486355        32691.0
4     10415.122150  10150.242763   7613.135754        38936.0
...            ...           ...           ...            ...
1283  22921.778114  19968.458775  19725.154453       274898.0
1284  22950.962403  20027.595507  19720.652033       275686.0
1285  22981.941569  20087.250271  19716.737125       370069.0
1286  23002.944295  20145.001693  19723.448202       355320.0
1287  23014.075507  20200.009267  19726.208299       278166.0

      market_cap_global  market_dominance  social_volume_global  \
0          2.455443e+11         69.345902              111697.0
1          2.486567e+11         69.119069              108047.0
2          2.488274e+11         69.313417               87587.0
3          2.511694e+11         69.581853               91851.0
4          2.642592e+11         70.133082              105847.0
...                 ...               ...                   ...
1283       1.028053e+12         41.982981             2630450.0
1284       1.022768e+12         42.357236             2241463.0
1285       1.024951e+12         42.257871             2278351.0
1286       1.024529e+12         41.881735             2244864.0
1287       1.017419e+12         41.224072             2224407.0

      social_dominance  Day of Month  month  Daily % Change  \
0            33.615048            29      8             NaN
1            32.784807            30      8        0.925039
2            34.040440            31      8        0.338504
3            35.591338             1      9        1.321887
4            36.785171             2      9        6.033944
...                ...           ...    ...             ...
1283         10.450607             4      3       -0.041718
1284         12.299378             5      3        0.367570
1285         16.242844             6      3       -0.025659
1286         15.828130             7      3       -0.936205
1287         12.505176             8      3       -2.257851

                          Date  S&P 500 Daily Performance  \
0    2019-08-29 00:00:00-04:00                   0.488253
1    2019-08-30 00:00:00-04:00                  -0.361927
2    2019-08-31 00:00:00-04:00                        NaN
3    2019-09-01 00:00:00-04:00                        NaN
4    2019-09-02 00:00:00-04:00                        NaN
...                        ...                        ...
1283 2023-03-04 00:00:00-05:00                        NaN
1284 2023-03-05 00:00:00-05:00                        NaN
1285 2023-03-06 00:00:00-05:00                  -0.165961
1286 2023-03-07 00:00:00-05:00                  -1.528802
1287                       NaT                        NaN

      NASDAQ 100 Daily Performance  1-Year Treasury Bond Rate  \
0                         0.307606                      1.940
1                        -0.674524                      1.933
2                              NaN                      1.933
3                              NaN                      1.933
4                              NaN                      1.933
...                            ...                        ...
1283                           NaN                      4.718
1284                           NaN                      4.718
1285                     -0.341605                      4.728
1286                     -1.227491                      4.845
1287                           NaN                        NaN

      5-Year Treasury Bond Rate  10-Year Treasury Bond Rate  \
0                         1.516                       1.516
1                         1.506                       1.506
2                         1.506                       1.506
3                         1.506                       1.506
4                         1.506                       1.506
...                         ...                         ...
1283                      3.964                       3.964
1284                      3.964                       3.964
1285                      3.983                       3.983
1286                      3.975                       3.975
1287                        NaN                         NaN

      30-Year Treasury Bond Rate  Bitcoin Futures Volume  \
0                          1.516                  4154.0
1                          1.506                  2856.0
2                          1.506                     NaN
3                          1.506                     NaN
4                          1.506                     NaN
...                          ...                     ...
1283                       3.964                     NaN
1284                       3.964                     NaN
1285                       3.983                  4800.0
1286                       3.975                  6742.0
1287                         NaN                     NaN

      Bitcoin Futures Returns
0                   -1.959773
1                    0.883789
2                         NaN
3                         NaN
4                         NaN
...                       ...
1283                      NaN
1284                      NaN
1285                -0.289468
1286                -1.714540
1287                      NaN

[1288 rows x 77 columns]

In [160]:
merged_df

,date,time,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_followers,tweet_quotes,tweet_retweets,tweet_replies,tweet_favorites,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,sentiment_absolute,sentiment_relative,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,alt_rank,alt_rank_30d,alt_rank_hour_average,market_cap_rank,percent_change_24h_rank,volume_24h_rank,social_volume_24h_rank,social_score_24h_rank,medium,youtube,social_contributors,influential_content,influential_content_score,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change,Date,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29,1567036800,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,NaN,NaN,NaN,NaN,NaN,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,NaN,NaN,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14178.0,NaN,NaN,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN,2019-08-29 00:00:00-04:00,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30,1567123200,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,NaN,NaN,NaN,NaN,NaN,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,NaN,NaN,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12955.0,NaN,NaN,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039,2019-08-30 00:00:00-04:00,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31,1567209600,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,NaN,NaN,NaN,NaN,NaN,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,NaN,NaN,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11277.0,NaN,NaN,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504,2019-08-31 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01,1567296000,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,NaN,NaN,NaN,NaN,NaN,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,NaN,NaN,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9597.0,NaN,NaN,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887,2019-09-01 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02,1567382400,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,NaN,NaN,NaN,NaN,NaN,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,NaN,NaN,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11568.0,NaN,NaN,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944,2019-09-02 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,2023-03-04,1677888000,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,9.264580e+08,3878.0,64823.0,36844.0,206599.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,3.0,93.0,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,137.0,22.0,261.83,1.0,2794.0,2.0,2.0,1.0,19.0,382.0,155477.0,809.0,629808.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718,2023-03-04 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05,1677974400,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,8.751753e+08,21741.0,59450.0,36262.0,224585.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,3.0,93.0,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,14.0,64.0,46.33,1.0,803.0,2.0,1.0,1.0,5.0,371.0,162513.0,888.0,702934.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570,2023-03-05 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06,1678060800,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,1.197015e+09,13853.0,90663.0,48067.0,300224.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,3.0,94.0,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,40.0,25.0,109.25,1.0,3118.0,2.0,2.0,1.0,9.0,469.0,231981.0,1359.0,1115135.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659,2023-03-06 00:00:00-05:00,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07,1678147200,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,1.374308e+09,4797.0,79405.0,46217.0,261429.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,3.0,94.0,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,65.0,60.0,158.58,1.0,3154.0,2.0,1.0,1.0,12.0,474.0,207784.0,1318.0,1062812.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205,2023-03-07 00:00:00-05:00,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540
1287,2023-03-08,1678233600,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,1.131440e+09,4434.0,71128.0,42789.0,253187.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,3.0,94.0,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,58.0,44.0,142.25,1.0,3214.0,2.0,2.0,1.0,5.0,481.0,186460.0,1240.0,973915.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
merged_df.to_csv('bigmerged_df.csv', index=False)

In [162]:
bigmerged_df = pd.read_csv('bigmerged_df.csv')

In [163]:
bigmerged_df

,date,time,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_followers,tweet_quotes,tweet_retweets,tweet_replies,tweet_favorites,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,sentiment_absolute,sentiment_relative,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,alt_rank,alt_rank_30d,alt_rank_hour_average,market_cap_rank,percent_change_24h_rank,volume_24h_rank,social_volume_24h_rank,social_score_24h_rank,medium,youtube,social_contributors,influential_content,influential_content_score,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change,Date,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29,1567036800,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,NaN,NaN,NaN,NaN,NaN,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,NaN,NaN,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14178.0,NaN,NaN,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN,2019-08-29 00:00:00-04:00,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30,1567123200,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,NaN,NaN,NaN,NaN,NaN,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,NaN,NaN,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12955.0,NaN,NaN,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039,2019-08-30 00:00:00-04:00,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31,1567209600,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,NaN,NaN,NaN,NaN,NaN,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,NaN,NaN,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11277.0,NaN,NaN,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504,2019-08-31 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01,1567296000,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,NaN,NaN,NaN,NaN,NaN,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,NaN,NaN,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9597.0,NaN,NaN,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887,2019-09-01 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02,1567382400,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,NaN,NaN,NaN,NaN,NaN,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,NaN,NaN,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11568.0,NaN,NaN,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944,2019-09-02 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,2023-03-04,1677888000,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,9.264580e+08,3878.0,64823.0,36844.0,206599.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,3.0,93.0,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,137.0,22.0,261.83,1.0,2794.0,2.0,2.0,1.0,19.0,382.0,155477.0,809.0,629808.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718,2023-03-04 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05,1677974400,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,8.751753e+08,21741.0,59450.0,36262.0,224585.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,3.0,93.0,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,14.0,64.0,46.33,1.0,803.0,2.0,1.0,1.0,5.0,371.0,162513.0,888.0,702934.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570,2023-03-05 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06,1678060800,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,1.197015e+09,13853.0,90663.0,48067.0,300224.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,3.0,94.0,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,40.0,25.0,109.25,1.0,3118.0,2.0,2.0,1.0,9.0,469.0,231981.0,1359.0,1115135.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659,2023-03-06 00:00:00-05:00,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07,1678147200,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,1.374308e+09,4797.0,79405.0,46217.0,261429.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,3.0,94.0,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,65.0,60.0,158.58,1.0,3154.0,2.0,1.0,1.0,12.0,474.0,207784.0,1318.0,1062812.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205,2023-03-07 00:00:00-05:00,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540
1287,2023-03-08,1678233600,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,1.131440e+09,4434.0,71128.0,42789.0,253187.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,3.0,94.0,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,58.0,44.0,142.25,1.0,3214.0,2.0,2.0,1.0,5.0,481.0,186460.0,1240.0,973915.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [164]:
# Print the column names for bigmerged_df
print(bigmerged_df.columns)

Index(['date', 'time', 'open', 'close', 'high', 'low', 'volume', 'volume_24h',
       'market_cap', 'circulating_supply', 'url_shares', 'unique_url_shares',
       'reddit_posts', 'reddit_posts_score', 'reddit_comments',
       'reddit_comments_score', 'tweets', 'tweet_spam', 'tweet_followers',
       'tweet_quotes', 'tweet_retweets', 'tweet_replies', 'tweet_favorites',
       'tweet_sentiment1', 'tweet_sentiment2', 'tweet_sentiment3',
       'tweet_sentiment4', 'tweet_sentiment5', 'tweet_sentiment_impact1',
       'tweet_sentiment_impact2', 'tweet_sentiment_impact3',
       'tweet_sentiment_impact4', 'tweet_sentiment_impact5', 'social_score',
       'average_sentiment', 'sentiment_absolute', 'sentiment_relative',
       'search_average', 'news', 'price_score', 'social_impact_score',
       'correlation_rank', 'galaxy_score', 'volatility', 'alt_rank',
       'alt_rank_30d', 'alt_rank_hour_average', 'market_cap_rank',
       'percent_change_24h_rank', 'volume_24h_rank', 'social_volume_24h_rank',
       'social_score_24h_rank', 'medium', 'youtube', 'social_contributors',
       'influential_content', 'influential_content_score', 'sma_50', 'sma_100',
       'sma_200', 'social_volume', 'market_cap_global', 'market_dominance',
       'social_volume_global', 'social_dominance', 'Day of Month', 'month',
       'Daily % Change', 'Date', 'S&P 500 Daily Performance',
       'NASDAQ 100 Daily Performance', '1-Year Treasury Bond Rate',
       '5-Year Treasury Bond Rate', '10-Year Treasury Bond Rate',
       '30-Year Treasury Bond Rate', 'Bitcoin Futures Volume',
       'Bitcoin Futures Returns'],
      dtype='object')

In [165]:
bigmerged_df.drop(columns=['tweet_followers', 'tweet_quotes', 'tweet_retweets', 'tweet_replies', 'tweet_favorites', 'alt_rank', 'alt_rank_30d', 'alt_rank_hour_average', 'market_cap_rank', 'percent_change_24h_rank', 'volume_24h_rank', 'social_volume_24h_rank', 'social_score_24h_rank', 'medium', 'youtube', 'influential_content', 'influential_content_score'], inplace=True)

In [166]:
bigmerged_df

,date,time,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,sentiment_absolute,sentiment_relative,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,social_contributors,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change,Date,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29,1567036800,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,NaN,NaN,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,14178.0,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN,2019-08-29 00:00:00-04:00,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30,1567123200,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,NaN,NaN,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,12955.0,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039,2019-08-30 00:00:00-04:00,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31,1567209600,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,NaN,NaN,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,11277.0,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504,2019-08-31 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01,1567296000,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,NaN,NaN,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,9597.0,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887,2019-09-01 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02,1567382400,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,NaN,NaN,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,11568.0,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944,2019-09-02 00:00:00-04:00,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,2023-03-04,1677888000,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,3.0,93.0,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,155477.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718,2023-03-04 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05,1677974400,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,3.0,93.0,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,162513.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570,2023-03-05 00:00:00-05:00,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06,1678060800,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,3.0,94.0,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,231981.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659,2023-03-06 00:00:00-05:00,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07,1678147200,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,3.0,94.0,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,207784.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205,2023-03-07 00:00:00-05:00,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540
1287,2023-03-08,1678233600,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,3.0,94.0,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,186460.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
bigmerged_df.drop(columns=['time', 'sentiment_absolute', 'sentiment_relative', 'Date'], inplace=True)
bigmerged_df

,date,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,social_contributors,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,14178.0,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,12955.0,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,11277.0,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,9597.0,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,11568.0,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,2023-03-04,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,155477.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,162513.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,231981.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,207784.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540
1287,2023-03-08,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,186460.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
bigmerged_df.to_csv('BitcoinData_master.csv', index=False)

In [169]:
BitcoinData_master_df = pd.read_csv('BitcoinData_master.csv')

In [170]:
BitcoinData_master_df

,date,open,close,high,low,volume,volume_24h,market_cap,circulating_supply,url_shares,unique_url_shares,reddit_posts,reddit_posts_score,reddit_comments,reddit_comments_score,tweets,tweet_spam,tweet_sentiment1,tweet_sentiment2,tweet_sentiment3,tweet_sentiment4,tweet_sentiment5,tweet_sentiment_impact1,tweet_sentiment_impact2,tweet_sentiment_impact3,tweet_sentiment_impact4,tweet_sentiment_impact5,social_score,average_sentiment,search_average,news,price_score,social_impact_score,correlation_rank,galaxy_score,volatility,social_contributors,sma_50,sma_100,sma_200,social_volume,market_cap_global,market_dominance,social_volume_global,social_dominance,Day of Month,month,Daily % Change,S&P 500 Daily Performance,NASDAQ 100 Daily Performance,1-Year Treasury Bond Rate,5-Year Treasury Bond Rate,10-Year Treasury Bond Rate,30-Year Treasury Bond Rate,Bitcoin Futures Volume,Bitcoin Futures Returns
0,2019-08-29,9756.785707,9510.200544,9756.785707,9421.630160,1.544143e+10,1.704588e+10,1.702749e+11,17902412,80.0,80.0,240.0,6980.0,1032.0,4684.0,35865.0,3580.0,1603.0,3430.0,6559.0,18886.0,1807.0,8651361.0,22634384.0,49073801.0,136696642.0,12868795.0,2.299354e+08,3.5,52.0,330.0,1.0,4.0,4.0,62.5,0.624617,14178.0,10524.912498,10072.925364,7489.222465,37547.0,2.455443e+11,69.345902,111697.0,33.615048,29,8,NaN,0.488253,0.307606,1.940,1.516,1.516,1.516,4154.0,-1.959773
1,2019-08-30,9514.844852,9598.173648,9656.123926,9428.302397,1.208824e+10,1.359526e+10,1.718692e+11,17904475,68.0,68.0,211.0,6366.0,1020.0,4781.0,33808.0,3350.0,1501.0,3083.0,6082.0,18090.0,1702.0,23926344.0,28730015.0,41017312.0,127370516.0,11893234.0,2.329465e+08,3.5,50.0,316.0,5.0,4.0,4.0,82.5,0.529363,12955.0,10489.702736,10092.106435,7518.971180,35423.0,2.486567e+11,69.119069,108047.0,32.784807,30,8,0.925039,-0.361927,-0.674524,1.933,1.506,1.506,1.506,2856.0,0.883789
2,2019-08-31,9597.539448,9630.663848,9673.220440,9531.799839,9.854216e+09,1.145481e+10,1.724707e+11,17906475,56.0,56.0,158.0,4306.0,828.0,3623.0,28603.0,3551.0,1147.0,2165.0,5504.0,14760.0,1476.0,33382004.0,38082040.0,31465126.0,100024109.0,7893289.0,2.108529e+08,3.5,43.0,170.0,4.2,4.0,4.0,78.5,0.151796,11277.0,10445.996280,10109.594606,7548.856856,29815.0,2.488274e+11,69.313417,87587.0,34.040440,31,8,0.338504,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
3,2019-09-01,9630.593196,9757.970318,9796.755968,9582.944631,9.730741e+09,1.144536e+10,1.747683e+11,17908500,56.0,56.0,150.0,5465.0,742.0,3347.0,31736.0,3664.0,1176.0,2528.0,5694.0,17046.0,1628.0,9017973.0,20622075.0,32667021.0,126860768.0,8962276.0,1.981383e+08,3.5,40.0,7.0,3.7,2.0,4.0,66.0,0.090203,9597.0,10413.308099,10127.300594,7579.486355,32691.0,2.511694e+11,69.581853,91851.0,35.591338,1,9,1.321887,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
4,2019-09-02,9757.473237,10346.760793,10396.591325,9730.650717,1.499891e+10,1.724810e+10,1.853331e+11,17910337,87.0,87.0,206.0,6785.0,1066.0,5620.0,37310.0,4161.0,1742.0,3207.0,6477.0,19967.0,1756.0,35499592.0,28099972.0,42822372.0,140741661.0,12325373.0,2.595008e+08,3.5,50.0,267.0,1.4,2.0,4.0,54.5,0.257690,11568.0,10415.122150,10150.242763,7613.135754,38936.0,2.642592e+11,70.133082,105847.0,36.785171,2,9,6.033944,NaN,NaN,1.933,1.506,1.506,1.506,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1283,2023-03-04,22362.923027,22353.350074,22405.176954,22198.981009,NaN,1.116601e+10,4.316073e+11,19308443,52255.0,4509.0,847.0,3405.0,2308.0,5591.0,267079.0,155619.0,498.0,9913.0,120831.0,133465.0,2372.0,7304761.0,81552672.0,307309761.0,520593633.0,10009332.0,9.268314e+08,3.5,NaN,155.0,1.0,3.0,1.0,42.4,0.020725,155477.0,22921.778114,19968.458775,19725.154453,274898.0,1.028053e+12,41.982981,2630450.0,10.450607,4,3,-0.041718,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1284,2023-03-05,22354.143598,22435.514197,22613.685231,22307.143313,NaN,1.331700e+10,4.332162e+11,19309437,41091.0,4141.0,716.0,6987.0,2513.0,6434.0,268189.0,174436.0,450.0,9059.0,124496.0,131222.0,2962.0,2287570.0,57981678.0,329460461.0,476534730.0,9252924.0,8.755719e+08,3.5,NaN,127.0,1.0,3.0,1.0,42.4,0.014853,162513.0,22950.962403,20027.595507,19720.652033,275686.0,1.022768e+12,42.357236,2241463.0,12.299378,5,3,0.367570,NaN,NaN,4.718,3.964,3.964,3.964,NaN,NaN
1285,2023-03-06,22436.816776,22429.757533,22584.293809,22331.314828,NaN,1.735319e+10,4.331225e+11,19310231,54697.0,6679.0,1105.0,4810.0,2847.0,10706.0,359141.0,222373.0,510.0,11580.0,150406.0,193006.0,3638.0,8728612.0,73404851.0,440109724.0,657819860.0,17404481.0,1.197538e+09,3.5,NaN,297.0,1.0,3.0,1.0,42.6,0.002277,231981.0,22981.941569,20087.250271,19716.737125,370069.0,1.024951e+12,42.257871,2278351.0,16.242844,6,3,-0.025659,-0.165961,-0.341605,4.728,3.983,3.983,3.983,4800.0,-0.289468
1286,2023-03-07,22428.322390,22219.769071,22527.418642,22011.262497,NaN,2.276545e+10,4.290907e+11,19311281,59540.0,6450.0,941.0,3944.0,2651.0,7502.0,344943.0,180947.0,507.0,11814.0,137035.0,192830.0,2757.0,10545582.0,72733817.0,592071450.0,681497291.0,17851746.0,1.374771e+09,3.5,NaN,335.0,1.0,3.0,1.0,42.7,0.003805,207784.0,23002.944295,20145.001693,19723.448202,355320.0,1.024529e+12,41.881735,2244864.0,15.828130,7,3,-0.936205,-1.528802,-1.227491,4.845,3.975,3.975,3.975,6742.0,-1.714540
1287,2023-03-08,22216.442321,21718.079830,22268.896252,21708.050506,NaN,2.253658e+10,4.194214e+11,19312112,55377.0,6215.0,983.0,4585.0,3651.0,8470.0,267005.0,207452.0,777.0,10301.0,93111.0,160587.0,2229.0,3439410.0,100168088.0,333766714.0,687105359.0,7331637.0,1.131880e+09,3.6,NaN,312.0,1.0,3.0,1.0,43.0,0.007676,186460.0,23014.075507,20200.009267,19726.208299,278166.0,1.017419e+12,41.224072,2224407.0,12.505176,8,3,-2.257851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [171]:
unique_values = df['average_sentiment'].unique()
print(unique_values)

[3.7 3.8 3.6 3.5 3.4 3.9 3.3 3.1 3. ]

In [2]:
import requests
import pandas as pd

start_date = '2019-08-28'
end_date = '2023-03-08'

url = f'https://api.blockchain.info/charts/difficulty?timespan=custom&start={start_date}&end={end_date}&format=json'
response = requests.get(url)
data = response.json()['values']

df = pd.DataFrame(data, columns=['x', 'y'])
df['date'] = pd.to_datetime(df['x'], unit='s').dt.date
df.drop('x', axis=1, inplace=True)
df.columns = ['difficulty', 'date']

print(df.head())

KeyError: 'values'

In [3]:
import nasdaqdatalink

In [4]:
import quandl
import pandas as pd

# Set the Quandl API key
quandl.ApiConfig.api_key = 'j1bxx9Kr2WVUiCkTus-u'

# Define the data products and time range
data_products = ['BCHAIN/AVBLS', 'BCHAIN/HRATE', 'BCHAIN/CPTRA', 'BCHAIN/DIFF']
start_date = '2019-08-28'
end_date = '2023-03-08'

# Retrieve the data for each data product and concatenate into a single dataframe
dfs = []
for product in data_products:
    df = quandl.get(product, start_date=start_date, end_date=end_date)
    df.columns = [product.split('/')[1]] # Rename the column to the data product code
    dfs.append(df)
df = pd.concat(dfs, axis=1)

# Convert the index to a datetime object and sort the dataframe by date
df.index = pd.to_datetime(df.index)
df = df.sort_index()

# Print the resulting dataframe
print(df)

               AVBLS         HRATE      CPTRA          DIFF
Date
2019-08-28  1.038467  7.643982e+07  56.521522  1.018349e+13
2019-08-29  0.995517  8.352695e+07  57.337225  1.018349e+13
2019-08-30  1.005411  8.099583e+07  55.423721  1.018349e+13
2019-08-31  0.874326  8.403318e+07  58.942276  1.018349e+13
2019-09-01  0.885620  7.595912e+07  60.905440  1.068557e+13
...              ...           ...        ...           ...
2023-03-04  2.145610  3.253132e+08  71.259805  4.305384e+13
2023-03-05  1.933651  3.317338e+08  77.165487  4.305384e+13
2023-03-06  1.809957  2.825088e+08  60.900910  4.305384e+13
2023-03-07  2.018769  3.531360e+08  65.223410  4.305384e+13
2023-03-08  1.980563  2.846490e+08  64.716008  4.305384e+13

[1289 rows x 4 columns]

In [ ]:


df

In [6]:
df.to_csv('mining_data.csv', index=True)

In [7]:
mining_df = pd.read_csv('mining_data.csv')

In [8]:
mining_df

            Date     AVBLS         HRATE      CPTRA          DIFF
0     2019-08-28  1.038467  7.643982e+07  56.521522  1.018349e+13
1     2019-08-29  0.995517  8.352695e+07  57.337225  1.018349e+13
2     2019-08-30  1.005411  8.099583e+07  55.423721  1.018349e+13
3     2019-08-31  0.874326  8.403318e+07  58.942276  1.018349e+13
4     2019-09-01  0.885620  7.595912e+07  60.905440  1.068557e+13
...          ...       ...           ...        ...           ...
1284  2023-03-04  2.145610  3.253132e+08  71.259805  4.305384e+13
1285  2023-03-05  1.933651  3.317338e+08  77.165487  4.305384e+13
1286  2023-03-06  1.809957  2.825088e+08  60.900910  4.305384e+13
1287  2023-03-07  2.018769  3.531360e+08  65.223410  4.305384e+13
1288  2023-03-08  1.980563  2.846490e+08  64.716008  4.305384e+13

[1289 rows x 5 columns]

In [10]:
import quandl

quandl.ApiConfig.api_key = 'YOUR_API_KEY'

data_products = ['BCHAIN/ETHUSD', 'BCHAIN/DOGEUSD', 'CHRIS/CME_SP1', 'CHRIS/CME_NQ1', 'CHRIS/CME_DX1', 'CHRIS/CME_YM1', 'CHRIS/ICE_T1', 'CHRIS/CBOE_VX1', 'YC/JPY10Y', 'USTREASURY/YIELD', 'CHRIS/CME_CL1']

start_date = '2020-01-01'
end_date = '2022-12-31'

dfs = []

for product in data_products:
    try:
        df = quandl.get(product, start_date=start_date, end_date=end_date)
        df.columns = [product.split('/')[1]] # Rename the column to the data product code
        dfs.append(df)
    except Exception as e:
        print(f"Error retrieving data for {product}: {str(e)}")

# Merge data frames into one data frame
merged_df = dfs[0]
for i in range(1, len(dfs)):
    merged_df = merged_df.merge(dfs[i], left_index=True, right_index=True, how='outer')

# Print the first few rows of the merged data frame
print(merged_df.head())

Error retrieving data for BCHAIN/ETHUSD: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for BCHAIN/DOGEUSD: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CME_SP1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CME_NQ1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CME_DX1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CME_YM1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/ICE_T1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CBOE_VX1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for YC/JPY10Y: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for USTREASURY/YIELD: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.
Error retrieving data for CHRIS/CME_CL1: (Status 429) (Quandl Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.

IndexError: list index out of range

In [2]:
import pandas as pd
import yfinance as yf

assets = ['ETH-USD', 'DOGE-USD']
start_date = '2019-08-28'
end_date = '2023-03-08'

dfs = []
for asset in assets:
    df = yf.download(asset, start=start_date, end=end_date, progress=False)
    df = df['Close'].rename(asset.replace('^', '').replace('-', '_'))
    dfs.append(df)
    
df_final = pd.concat(dfs, axis=1)
print(df_final.head())

                              ETH_USD  DOGE_USD
Date
2019-08-28 00:00:00+00:00  173.889969  0.002524
2019-08-29 00:00:00+00:00  169.516739  0.002450
2019-08-30 00:00:00+00:00  168.834869  0.002482
2019-08-31 00:00:00+00:00  172.469788  0.002511
2019-09-01 00:00:00+00:00  171.629425  0.002492

In [3]:
df_final

                               ETH_USD  DOGE_USD
Date
2019-08-28 00:00:00+00:00   173.889969  0.002524
2019-08-29 00:00:00+00:00   169.516739  0.002450
2019-08-30 00:00:00+00:00   168.834869  0.002482
2019-08-31 00:00:00+00:00   172.469788  0.002511
2019-09-01 00:00:00+00:00   171.629425  0.002492
...                                ...       ...
2023-03-03 00:00:00+00:00  1569.167603  0.076777
2023-03-04 00:00:00+00:00  1566.923950  0.074556
2023-03-05 00:00:00+00:00  1564.468750  0.074795
2023-03-06 00:00:00+00:00  1567.398682  0.074805
2023-03-07 00:00:00+00:00  1561.933105  0.074048

[1288 rows x 2 columns]

In [25]:
df_final

                               ETH_USD  DOGE_USD
Date
2019-08-28 00:00:00+00:00   173.889969  0.002524
2019-08-29 00:00:00+00:00   169.516739  0.002450
2019-08-30 00:00:00+00:00   168.834869  0.002482
2019-08-31 00:00:00+00:00   172.469788  0.002511
2019-09-01 00:00:00+00:00   171.629425  0.002492
...                                ...       ...
2023-03-03 00:00:00+00:00  1569.167603  0.076777
2023-03-04 00:00:00+00:00  1566.923950  0.074556
2023-03-05 00:00:00+00:00  1564.468750  0.074795
2023-03-06 00:00:00+00:00  1567.398682  0.074805
2023-03-07 00:00:00+00:00  1561.933105  0.074048

[1288 rows x 2 columns]

In [5]:
df_final.to_csv('ETHDOGE.csv', index=True)

In [7]:
ETHDOGE_df = pd.read_csv('ETHDOGE.csv')

In [8]:
ETHDOGE_df

                           Date      ETH_USD  DOGE_USD
0     2019-08-28 00:00:00+00:00   173.889969  0.002524
1     2019-08-29 00:00:00+00:00   169.516739  0.002450
2     2019-08-30 00:00:00+00:00   168.834869  0.002482
3     2019-08-31 00:00:00+00:00   172.469788  0.002511
4     2019-09-01 00:00:00+00:00   171.629425  0.002492
...                         ...          ...       ...
1283  2023-03-03 00:00:00+00:00  1569.167603  0.076777
1284  2023-03-04 00:00:00+00:00  1566.923950  0.074556
1285  2023-03-05 00:00:00+00:00  1564.468750  0.074795
1286  2023-03-06 00:00:00+00:00  1567.398682  0.074805
1287  2023-03-07 00:00:00+00:00  1561.933105  0.074048

[1288 rows x 3 columns]

In [15]:
import yfinance as yf
import pandas as pd

assets = ['^N225', '^GSPC', '000300.SS', 'DX-Y.NYB', '^DJI', 'CL=F', '^IXIC']
start_date = '2022-03-01'
end_date = '2022-03-11'
dfs = []

for asset in assets:
    try:
        df = yf.download(asset, start=start_date, end=end_date, interval='1d', progress=False, ignore_tz=True, prepost=False)
        df.columns = [asset.replace('^', '') if '^' in asset else asset.replace('-', '_')] # Rename the column to the asset name
        dfs.append(df['Close'])
    except:
        print(f"Failed to download data for {asset}")

df_final2 = pd.concat(dfs, axis=1)

Failed to download data for ^N225
Failed to download data for ^GSPC
Failed to download data for 000300.SS
Failed to download data for DX-Y.NYB
Failed to download data for ^DJI
Failed to download data for CL=F
Failed to download data for ^IXIC

ValueError: No objects to concatenate

In [16]:
from alpha_vantage.timeseries import TimeSeries

api_key = 'XPPJ9T1WLPM2L360'

ts = TimeSeries(api_key, output_format='pandas')

In [17]:
assets = ['^N225', '^GSPC', '000300.SS', 'DX-Y.NYB', '^DJI', 'CL=F', '^IXIC']

In [18]:
import requests

url = "https://u-s-economic-indicators.p.rapidapi.com/api/v1/resources/M2-sa-monthly"

headers = {
    "X-RapidAPI-Key": "40d3a7f43cmshb0c6326b8f21b2cp1f3f76jsn6989f38dacf4",
    "X-RapidAPI-Host": "u-s-economic-indicators.p.rapidapi.com"
}

start_date = "2019-08-28"
end_date = "2023-03-08"

querystring = {"start_date": start_date, "end_date": end_date}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{
  "H6 M2 Money Stock Measure": {
    "1959-01-31": 286.6,
    "1959-02-28": 287.7,
    "1959-03-31": 289.2,
    "1959-04-30": 290.1,
    "1959-05-31": 292.2,
    "1959-06-30": 294.1,
    "1959-07-31": 295.2,
    "1959-08-31": 296.4,
    "1959-09-30": 296.7,
    "1959-10-31": 296.5,
    "1959-11-30": 297.1,
    "1959-12-31": 297.8,
    "1960-01-31": 298.2,
    "1960-02-29": 298.4,
    "1960-03-31": 299.3,
    "1960-04-30": 300.1,
    "1960-05-31": 300.9,
    "1960-06-30": 302.3,
    "1960-07-31": 304.1,
    "1960-08-31": 306.9,
    "1960-09-30": 308.4,
    "1960-10-31": 309.5,
    "1960-11-30": 310.9,
    "1960-12-31": 312.4,
    "1961-01-31": 314.1,
    "1961-02-28": 316.5,
    "1961-03-31": 318.3,
    "1961-04-30": 319.9,
    "1961-05-31": 322.2,
    "1961-06-30": 324.3,
    "1961-07-31": 325.6,
    "1961-08-31": 327.6,
    "1961-09-30": 329.5,
    "1961-10-31": 331.1,
    "1961-11-30": 333.4,
    "1961-12-31": 335.5,
    "1962-01-31": 337.5,
    "1962-02-28": 340.1,
    "1962-03-31": 343.1,
    "1962-04-30": 345.5,
    "1962-05-31": 347.5,
    "1962-06-30": 349.3,
    "1962-07-31": 350.8,
    "1962-08-31": 352.8,
    "1962-09-30": 354.9,
    "1962-10-31": 357.2,
    "1962-11-30": 359.8,
    "1962-12-31": 362.7,
    "1963-01-31": 365.2,
    "1963-02-28": 367.9,
    "1963-03-31": 370.7,
    "1963-04-30": 373.3,
    "1963-05-31": 376.1,
    "1963-06-30": 378.4,
    "1963-07-31": 381.1,
    "1963-08-31": 383.6,
    "1963-09-30": 386.0,
    "1963-10-31": 388.3,
    "1963-11-30": 391.5,
    "1963-12-31": 393.2,
    "1964-01-31": 395.2,
    "1964-02-29": 397.6,
    "1964-03-31": 399.8,
    "1964-04-30": 401.7,
    "1964-05-31": 404.2,
    "1964-06-30": 407.1,
    "1964-07-31": 410.1,
    "1964-08-31": 413.4,
    "1964-09-30": 416.9,
    "1964-10-31": 419.1,
    "1964-11-30": 422.0,
    "1964-12-31": 424.7,
    "1965-01-31": 427.5,
    "1965-02-28": 430.4,
    "1965-03-31": 433.2,
    "1965-04-30": 435.4,
    "1965-05-31": 437.1,
    "1965-06-30": 440.1,
    "1965-07-31": 442.9,
    "1965-08-31": 445.8,
    "1965-09-30": 449.5,
    "1965-10-31": 452.6,
    "1965-11-30": 455.7,
    "1965-12-31": 459.2,
    "1966-01-31": 462.0,
    "1966-02-28": 464.6,
    "1966-03-31": 467.2,
    "1966-04-30": 469.3,
    "1966-05-31": 470.1,
    "1966-06-30": 471.2,
    "1966-07-31": 470.9,
    "1966-08-31": 472.6,
    "1966-09-30": 475.4,
    "1966-10-31": 475.7,
    "1966-11-30": 477.3,
    "1966-12-31": 480.2,
    "1967-01-31": 481.6,
    "1967-02-28": 485.1,
    "1967-03-31": 489.7,
    "1967-04-30": 492.1,
    "1967-05-31": 497.2,
    "1967-06-30": 502.0,
    "1967-07-31": 506.3,
    "1967-08-31": 510.8,
    "1967-09-30": 514.7,
    "1967-10-31": 518.2,
    "1967-11-30": 521.2,
    "1967-12-31": 524.8,
    "1968-01-31": 527.4,
    "1968-02-29": 530.4,
    "1968-03-31": 533.2,
    "1968-04-30": 535.7,
    "1968-05-31": 538.9,
    "1968-06-30": 542.6,
    "1968-07-31": 545.6,
    "1968-08-31": 549.4,
    "1968-09-30": 553.6,
    "1968-10-31": 557.6,
    "1968-11-30": 562.4,
    "1968-12-31": 566.8,
    "1969-01-31": 569.3,
    "1969-02-28": 571.9,
    "1969-03-31": 574.4,
    "1969-04-30": 575.7,
    "1969-05-31": 576.5,
    "1969-06-30": 578.5,
    "1969-07-31": 579.5,
    "1969-08-31": 580.1,
    "1969-09-30": 582.1,
    "1969-10-31": 583.4,
    "1969-11-30": 585.4,
    "1969-12-31": 587.9,
    "1970-01-31": 589.6,
    "1970-02-28": 586.3,
    "1970-03-31": 587.3,
    "1970-04-30": 588.4,
    "1970-05-31": 591.5,
    "1970-06-30": 595.2,
    "1970-07-31": 599.1,
    "1970-08-31": 604.9,
    "1970-09-30": 611.2,
    "1970-10-31": 616.4,
    "1970-11-30": 621.1,
    "1970-12-31": 626.5,
    "1971-01-31": 632.9,
    "1971-02-28": 641.0,
    "1971-03-31": 649.9,
    "1971-04-30": 658.4,
    "1971-05-31": 666.7,
    "1971-06-30": 673.0,
    "1971-07-31": 679.6,
    "1971-08-31": 685.5,
    "1971-09-30": 692.5,
    "1971-10-31": 698.4,
    "1971-11-30": 704.6,
    "1971-12-31": 710.3,
    "1972-01-31": 717.7,
    "1972-02-29": 725.7,
    "1972-03-31": 733.5,
    "1972-04-30": 738.4,
    "1972-05-31": 743.3,
    "1972-06-30": 749.7,
    "1972-07-31": 759.5,
    "1972-08-31": 768.7,
    "1972-09-30": 778.3,
    "1972-10-31": 786.9,
    "1972-11-30": 793.9,
    "1972-12-31": 802.3,
    "1973-01-31": 810.3,
    "1973-02-28": 814.1,
    "1973-03-31": 815.3,
    "1973-04-30": 819.7,
    "1973-05-31": 826.8,
    "1973-06-30": 833.3,
    "1973-07-31": 836.5,
    "1973-08-31": 838.8,
    "1973-09-30": 839.3,
    "1973-10-31": 842.6,
    "1973-11-30": 848.9,
    "1973-12-31": 855.5,
    "1974-01-31": 859.7,
    "1974-02-28": 864.2,
    "1974-03-31": 870.1,
    "1974-04-30": 872.9,
    "1974-05-31": 874.6,
    "1974-06-30": 877.8,
    "1974-07-31": 881.4,
    "1974-08-31": 884.1,
    "1974-09-30": 887.9,
    "1974-10-31": 893.3,
    "1974-11-30": 898.6,
    "1974-12-31": 902.1,
    "1975-01-31": 906.3,
    "1975-02-28": 914.1,
    "1975-03-31": 925.0,
    "1975-04-30": 935.1,
    "1975-05-31": 947.9,
    "1975-06-30": 963.0,
    "1975-07-31": 975.1,
    "1975-08-31": 983.1,
    "1975-09-30": 991.5,
    "1975-10-31": 997.8,
    "1975-11-30": 1006.9,
    "1975-12-31": 1016.2,
    "1976-01-31": 1026.6,
    "1976-02-29": 1040.3,
    "1976-03-31": 1050.0,
    "1976-04-30": 1060.8,
    "1976-05-31": 1072.1,
    "1976-06-30": 1077.6,
    "1976-07-31": 1086.3,
    "1976-08-31": 1098.7,
    "1976-09-30": 1110.8,
    "1976-10-31": 1125.0,
    "1976-11-30": 1138.2,
    "1976-12-31": 1152.0,
    "1977-01-31": 1165.2,
    "1977-02-28": 1177.6,
    "1977-03-31": 1188.5,
    "1977-04-30": 1199.6,
    "1977-05-31": 1209.0,
    "1977-06-30": 1217.8,
    "1977-07-31": 1226.7,
    "1977-08-31": 1237.0,
    "1977-09-30": 1246.2,
    "1977-10-31": 1254.0,
    "1977-11-30": 1262.4,
    "1977-12-31": 1270.3,
    "1978-01-31": 1279.7,
    "1978-02-28": 1285.5,
    "1978-03-31": 1292.2,
    "1978-04-30": 1300.4,
    "1978-05-31": 1310.5,
    "1978-06-30": 1318.5,
    "1978-07-31": 1324.1,
    "1978-08-31": 1333.5,
    "1978-09-30": 1345.0,
    "1978-10-31": 1352.3,
    "1978-11-30": 1359.1,
    "1978-12-31": 1366.0,
    "1979-01-31": 1371.6,
    "1979-02-28": 1377.8,
    "1979-03-31": 1387.8,
    "1979-04-30": 1402.1,
    "1979-05-31": 1410.2,
    "1979-06-30": 1423.0,
    "1979-07-31": 1434.8,
    "1979-08-31": 1446.6,
    "1979-09-30": 1454.1,
    "1979-10-31": 1460.4,
    "1979-11-30": 1465.9,
    "1979-12-31": 1473.7,
    "1980-01-31": 1482.7,
    "1980-02-29": 1494.6,
    "1980-03-31": 1499.8,
    "1980-04-30": 1502.2,
    "1980-05-31": 1512.3,
    "1980-06-30": 1529.2,
    "1980-07-31": 1545.5,
    "1980-08-31": 1561.5,
    "1980-09-30": 1574.0,
    "1980-10-31": 1584.8,
    "1980-11-30": 1595.8,
    "1980-12-31": 1599.8,
    "1981-01-31": 1606.9,
    "1981-02-28": 1618.7,
    "1981-03-31": 1636.6,
    "1981-04-30": 1659.2,
    "1981-05-31": 1664.2,
    "1981-06-30": 1670.3,
    "1981-07-31": 1681.9,
    "1981-08-31": 1694.3,
    "1981-09-30": 1706.0,
    "1981-10-31": 1721.8,
    "1981-11-30": 1736.1,
    "1981-12-31": 1755.5,
    "1982-01-31": 1770.4,
    "1982-02-28": 1774.5,
    "1982-03-31": 1786.5,
    "1982-04-30": 1803.9,
    "1982-05-31": 1815.4,
    "1982-06-30": 1826.0,
    "1982-07-31": 1831.5,
    "1982-08-31": 1845.2,
    "1982-09-30": 1858.4,
    "1982-10-31": 1869.7,
    "1982-11-30": 1883.7,
    "1982-12-31": 1905.9,
    "1983-01-31": 1959.4,
    "1983-02-28": 1996.8,
    "1983-03-31": 2015.2,
    "1983-04-30": 2028.6,
    "1983-05-31": 2043.1,
    "1983-06-30": 2053.5,
    "1983-07-31": 2064.8,
    "1983-08-31": 2074.0,
    "1983-09-30": 2083.2,
    "1983-10-31": 2099.2,
    "1983-11-30": 2112.3,
    "1983-12-31": 2123.5,
    "1984-01-31": 2138.2,
    "1984-02-29": 2158.2,
    "1984-03-31": 2175.2,
    "1984-04-30": 2191.7,
    "1984-05-31": 2204.1,
    "1984-06-30": 2215.1,
    "1984-07-31": 2223.5,
    "1984-08-31": 2230.4,
    "1984-09-30": 2244.4,
    "1984-10-31": 2258.9,
    "1984-11-30": 2281.4,
    "1984-12-31": 2306.4,
    "1985-01-31": 2332.4,
    "1985-02-28": 2354.1,
    "1985-03-31": 2366.2,
    "1985-04-30": 2375.4,
    "1985-05-31": 2389.5,
    "1985-06-30": 2412.6,
    "1985-07-31": 2429.5,
    "1985-08-31": 2444.0,
    "1985-09-30": 2456.4,
    "1985-10-31": 2468.0,
    "1985-11-30": 2477.8,
    "1985-12-31": 2492.1,
    "1986-01-31": 2502.1,
    "1986-02-28": 2512.9,
    "1986-03-31": 2533.1,
    "1986-04-30": 2557.8,
    "1986-05-31": 2584.8,
    "1986-06-30": 2605.0,
    "1986-07-31": 2626.6,
    "1986-08-31": 2646.5,
    "1986-09-30": 2667.8,
    "1986-10-31": 2687.4,
    "1986-11-30": 2701.3,
    "1986-12-31": 2728.0,
    "1987-01-31": 2743.9,
    "1987-02-28": 2747.5,
    "1987-03-31": 2753.7,
    "1987-04-30": 2767.7,
    "1987-05-31": 2772.9,
    "1987-06-30": 2774.6,
    "1987-07-31": 2779.0,
    "1987-08-31": 2788.2,
    "1987-09-30": 2799.5,
    "1987-10-31": 2814.8,
    "1987-11-30": 2818.9,
    "1987-12-31": 2826.4,
    "1988-01-31": 2847.4,
    "1988-02-29": 2870.4,
    "1988-03-31": 2890.7,
    "1988-04-30": 2910.7,
    "1988-05-31": 2926.0,
    "1988-06-30": 2938.4,
    "1988-07-31": 2947.2,
    "1988-08-31": 2952.0,
    "1988-09-30": 2956.9,
    "1988-10-31": 2965.3,
    "1988-11-30": 2980.2,
    "1988-12-31": 2988.2,
    "1989-01-31": 2991.7,
    "1989-02-28": 2992.2,
    "1989-03-31": 2999.7,
    "1989-04-30": 3006.0,
    "1989-05-31": 3011.6,
    "1989-06-30": 3027.9,
    "1989-07-31": 3052.4,
    "1989-08-31": 3074.4,
    "1989-09-30": 3092.5,
    "1989-10-31": 3114.1,
    "1989-11-30": 3133.3,
    "1989-12-31": 3152.5,
    "1990-01-31": 3166.8,
    "1990-02-28": 3179.2,
    "1990-03-31": 3190.1,
    "1990-04-30": 3201.6,
    "1990-05-31": 3200.6,
    "1990-06-30": 3213.7,
    "1990-07-31": 3224.5,
    "1990-08-31": 3242.0,
    "1990-09-30": 3254.6,
    "1990-10-31": 3259.3,
    "1990-11-30": 3262.6,
    "1990-12-31": 3271.8,
    "1991-01-31": 3287.7,
    "1991-02-28": 3304.5,
    "1991-03-31": 3321.9,
    "1991-04-30": 3332.4,
    "1991-05-31": 3343.0,
    "1991-06-30": 3351.9,
    "1991-07-31": 3356.1,
    "1991-08-31": 3355.0,
    "1991-09-30": 3354.9,
    "1991-10-31": 3360.1,
    "1991-11-30": 3365.5,
    "1991-12-31": 3372.2,
    "1992-01-31": 3381.2,
    "1992-02-29": 3400.0,
    "1992-03-31": 3403.9,
    "1992-04-30": 3399.7,
    "1992-05-31": 3398.6,
    "1992-06-30": 3393.4,
    "1992-07-31": 3393.9,
    "1992-08-31": 3398.8,
    "1992-09-30": 3410.3,
    "1992-10-31": 3423.8,
    "1992-11-30": 3426.5,
    "1992-12-31": 3424.7,
    "1993-01-31": 3419.1,
    "1993-02-28": 3414.5,
    "1993-03-31": 3411.7,
    "1993-04-30": 3411.3,
    "1993-05-31": 3436.9,
    "1993-06-30": 3442.4,
    "1993-07-31": 3442.0,
    "1993-08-31": 3445.7,
    "1993-09-30": 3452.2,
    "1993-10-31": 3456.7,
    "1993-11-30": 3470.1,
    "1993-12-31": 3474.5,
    "1994-01-31": 3474.9,
    "1994-02-28": 3475.7,
    "1994-03-31": 3480.1,
    "1994-04-30": 3481.3,
    "1994-05-31": 3490.8,
    "1994-06-30": 3479.5,
    "1994-07-31": 3488.2,
    "1994-08-31": 3485.7,
    "1994-09-30": 3486.1,
    "1994-10-31": 3484.3,
    "1994-11-30": 3487.2,
    "1994-12-31": 3486.4,
    "1995-01-31": 3492.4,
    "1995-02-28": 3489.9,
    "1995-03-31": 3491.1,
    "1995-04-30": 3499.2,
    "1995-05-31": 3524.2,
    "1995-06-30": 3548.9,
    "1995-07-31": 3567.4,
    "1995-08-31": 3589.0,
    "1995-09-30": 3602.1,
    "1995-10-31": 3613.4,
    "1995-11-30": 3619.9,
    "1995-12-31": 3629.5,
    "1996-01-31": 3647.9,
    "1996-02-29": 3661.8,
    "1996-03-31": 3686.9,
    "1996-04-30": 3697.7,
    "1996-05-31": 3709.6,
    "1996-06-30": 3722.5,
    "1996-07-31": 3737.1,
    "1996-08-31": 3744.0,
    "1996-09-30": 3753.4,
    "1996-10-31": 3772.8,
    "1996-11-30": 3795.1,
    "1996-12-31": 3818.6,
    "1997-01-31": 3834.6,
    "1997-02-28": 3846.3,
    "1997-03-31": 3861.2,
    "1997-04-30": 3877.0,
    "1997-05-31": 3889.2,
    "1997-06-30": 3906.0,
    "1997-07-31": 3923.9,
    "1997-08-31": 3957.4,
    "1997-09-30": 3973.1,
    "1997-10-31": 3992.3,
    "1997-11-30": 4014.8,
    "1997-12-31": 4032.9,
    "1998-01-31": 4056.2,
    "1998-02-28": 4088.9,
    "1998-03-31": 4114.3,
    "1998-04-30": 4140.2,
    "1998-05-31": 4164.4,
    "1998-06-30": 4184.1,
    "1998-07-31": 4203.8,
    "1998-08-31": 4228.7,
    "1998-09-30": 4267.6,
    "1998-10-31": 4307.7,
    "1998-11-30": 4346.4,
    "1998-12-31": 4375.2,
    "1999-01-31": 4402.6,
    "1999-02-28": 4425.3,
    "1999-03-31": 4432.1,
    "1999-04-30": 4460.7,
    "1999-05-31": 4485.3,
    "1999-06-30": 4507.2,
    "1999-07-31": 4534.5,
    "1999-08-31": 4551.7,
    "1999-09-30": 4567.7,
    "1999-10-31": 4591.5,
    "1999-11-30": 4610.5,
    "1999-12-31": 4638.0,
    "2000-01-31": 4666.2,
    "2000-02-29": 4679.4,
    "2000-03-31": 4710.2,
    "2000-04-30": 4766.1,
    "2000-05-31": 4753.9,
    "2000-06-30": 4771.8,
    "2000-07-31": 4789.4,
    "2000-08-31": 4817.5,
    "2000-09-30": 4853.2,
    "2000-10-31": 4869.2,
    "2000-11-30": 4880.3,
    "2000-12-31": 4925.0,
    "2001-01-31": 4975.7,
    "2001-02-28": 5014.1,
    "2001-03-31": 5072.0,
    "2001-04-30": 5135.9,
    "2001-05-31": 5133.0,
    "2001-06-30": 5173.5,
    "2001-07-31": 5203.4,
    "2001-08-31": 5237.2,
    "2001-09-30": 5348.4,
    "2001-10-31": 5337.1,
    "2001-11-30": 5380.8,
    "2001-12-31": 5433.8,
    "2002-01-31": 5454.1,
    "2002-02-28": 5483.4,
    "2002-03-31": 5495.2,
    "2002-04-30": 5495.4,
    "2002-05-31": 5521.5,
    "2002-06-30": 5546.5,
    "2002-07-31": 5589.1,
    "2002-08-31": 5631.6,
    "2002-09-30": 5656.0,
    "2002-10-31": 5700.4,
    "2002-11-30": 5750.6,
    "2002-12-31": 5772.0,
    "2003-01-31": 5804.6,
    "2003-02-28": 5840.7,
    "2003-03-31": 5861.4,
    "2003-04-30": 5898.8,
    "2003-05-31": 5959.3,
    "2003-06-30": 5996.0,
    "2003-07-31": 6042.7,
    "2003-08-31": 6100.8,
    "2003-09-30": 6072.8,
    "2003-10-31": 6063.6,
    "2003-11-30": 6069.1,
    "2003-12-31": 6067.3,
    "2004-01-31": 6075.5,
    "2004-02-29": 6114.3,
    "2004-03-31": 6150.1,
    "2004-04-30": 6191.2,
    "2004-05-31": 6268.1,
    "2004-06-30": 6270.5,
    "2004-07-31": 6284.3,
    "2004-08-31": 6310.6,
    "2004-09-30": 6345.3,
    "2004-10-31": 6373.3,
    "2004-11-30": 6399.8,
    "2004-12-31": 6418.3,
    "2005-01-31": 6424.5,
    "2005-02-28": 6432.8,
    "2005-03-31": 6441.9,
    "2005-04-30": 6455.9,
    "2005-05-31": 6473.3,
    "2005-06-30": 6505.8,
    "2005-07-31": 6537.4,
    "2005-08-31": 6570.2,
    "2005-09-30": 6604.3,
    "2005-10-31": 6638.6,
    "2005-11-30": 6655.0,
    "2005-12-31": 6681.9,
    "2006-01-31": 6724.3,
    "2006-02-28": 6748.6,
    "2006-03-31": 6762.9,
    "2006-04-30": 6800.1,
    "2006-05-31": 6806.9,
    "2006-06-30": 6844.9,
    "2006-07-31": 6886.3,
    "2006-08-31": 6917.1,
    "2006-09-30": 6944.2,
    "2006-10-31": 6993.3,
    "2006-11-30": 7028.4,
    "2006-12-31": 7071.6,
    "2007-01-31": 7109.6,
    "2007-02-28": 7125.3,
    "2007-03-31": 7159.1,
    "2007-04-30": 7231.3,
    "2007-05-31": 7245.4,
    "2007-06-30": 7278.6,
    "2007-07-31": 7309.0,
    "2007-08-31": 7385.1,
    "2007-09-30": 7403.2,
    "2007-10-31": 7417.2,
    "2007-11-30": 7441.8,
    "2007-12-31": 7471.6,
    "2008-01-31": 7505.5,
    "2008-02-29": 7590.6,
    "2008-03-31": 7656.2,
    "2008-04-30": 7699.2,
    "2008-05-31": 7711.2,
    "2008-06-30": 7728.9,
    "2008-07-31": 7775.4,
    "2008-08-31": 7790.2,
    "2008-09-30": 7859.5,
    "2008-10-31": 7965.3,
    "2008-11-30": 8015.8,
    "2008-12-31": 8192.1,
    "2009-01-31": 8273.7,
    "2009-02-28": 8303.1,
    "2009-03-31": 8369.3,
    "2009-04-30": 8372.9,
    "2009-05-31": 8430.7,
    "2009-06-30": 8440.5,
    "2009-07-31": 8445.1,
    "2009-08-31": 8445.0,
    "2009-09-30": 8444.2,
    "2009-10-31": 8471.1,
    "2009-11-30": 8500.8,
    "2009-12-31": 8496.0,
    "2010-01-31": 8458.1,
    "2010-02-28": 8507.4,
    "2010-03-31": 8504.5,
    "2010-04-30": 8535.2,
    "2010-05-31": 8589.9,
    "2010-06-30": 8609.0,
    "2010-07-31": 8618.8,
    "2010-08-31": 8669.1,
    "2010-09-30": 8700.1,
    "2010-10-31": 8749.4,
    "2010-11-30": 8770.0,
    "2010-12-31": 8801.8,
    "2011-01-31": 8823.1,
    "2011-02-28": 8886.9,
    "2011-03-31": 8943.5,
    "2011-04-30": 9004.9,
    "2011-05-31": 9075.5,
    "2011-06-30": 9151.0,
    "2011-07-31": 9316.6,
    "2011-08-31": 9507.6,
    "2011-09-30": 9528.3,
    "2011-10-31": 9562.1,
    "2011-11-30": 9612.6,
    "2011-12-31": 9660.1,
    "2012-01-31": 9733.3,
    "2012-02-29": 9785.7,
    "2012-03-31": 9830.6,
    "2012-04-30": 9884.6,
    "2012-05-31": 9928.4,
    "2012-06-30": 9999.3,
    "2012-07-31": 10051.8,
    "2012-08-31": 10121.3,
    "2012-09-30": 10200.8,
    "2012-10-31": 10267.3,
    "2012-11-30": 10337.6,
    "2012-12-31": 10459.7,
    "2013-01-31": 10479.5,
    "2013-02-28": 10482.0,
    "2013-03-31": 10550.0,
    "2013-04-30": 10585.9,
    "2013-05-31": 10628.2,
    "2013-06-30": 10684.9,
    "2013-07-31": 10730.8,
    "2013-08-31": 10790.2,
    "2013-09-30": 10841.3,
    "2013-10-31": 10956.7,
    "2013-11-30": 10969.0,
    "2013-12-31": 11028.8,
    "2014-01-31": 11078.9,
    "2014-02-28": 11161.0,
    "2014-03-31": 11200.2,
    "2014-04-30": 11256.9,
    "2014-05-31": 11326.3,
    "2014-06-30": 11380.7,
    "2014-07-31": 11439.9,
    "2014-08-31": 11469.4,
    "2014-09-30": 11502.8,
    "2014-10-31": 11563.4,
    "2014-11-30": 11604.7,
    "2014-12-31": 11681.5,
    "2015-01-31": 11745.2,
    "2015-02-28": 11863.9,
    "2015-03-31": 11879.6,
    "2015-04-30": 11927.4,
    "2015-05-31": 11960.3,
    "2015-06-30": 12005.8,
    "2015-07-31": 12058.4,
    "2015-08-31": 12109.5,
    "2015-09-30": 12164.5,
    "2015-10-31": 12196.8,
    "2015-11-30": 12286.0,
    "2015-12-31": 12344.0,
    "2016-01-31": 12470.0,
    "2016-02-29": 12545.6,
    "2016-03-31": 12609.7,
    "2016-04-30": 12698.4,
    "2016-05-31": 12765.6,
    "2016-06-30": 12831.9,
    "2016-07-31": 12892.0,
    "2016-08-31": 12978.2,
    "2016-09-30": 13037.9,
    "2016-10-31": 13105.4,
    "2016-11-30": 13176.5,
    "2016-12-31": 13209.6,
    "2017-01-31": 13282.7,
    "2017-02-28": 13351.4,
    "2017-03-31": 13420.6,
    "2017-04-30": 13482.9,
    "2017-05-31": 13534.8,
    "2017-06-30": 13558.9,
    "2017-07-31": 13621.0,
    "2017-08-31": 13679.6,
    "2017-09-30": 13722.1,
    "2017-10-31": 13777.4,
    "2017-11-30": 13804.1,
    "2017-12-31": 13852.3,
    "2018-01-31": 13868.2,
    "2018-02-28": 13910.2,
    "2018-03-31": 13965.5,
    "2018-04-30": 13987.7,
    "2018-05-31": 14041.2,
    "2018-06-30": 14102.6,
    "2018-07-31": 14137.0,
    "2018-08-31": 14187.4,
    "2018-09-30": 14214.6,
    "2018-10-31": 14228.5,
    "2018-11-30": 14241.6,
    "2018-12-31": 14358.8,
    "2019-01-31": 14430.8,
    "2019-02-28": 14472.3,
    "2019-03-31": 14510.7,
    "2019-04-30": 14541.0,
    "2019-05-31": 14632.5,
    "2019-06-30": 14754.8,
    "2019-07-31": 14833.8,
    "2019-08-31": 14919.8,
    "2019-09-30": 15004.8,
    "2019-10-31": 15144.2,
    "2019-11-30": 15249.9,
    "2019-12-31": 15319.1,
    "2020-01-31": 15401.8,
    "2020-02-29": 15457.9,
    "2020-03-31": 15984.1,
    "2020-04-30": 16997.9,
    "2020-05-31": 17830.8,
    "2020-06-30": 18124.6,
    "2020-07-31": 18273.2,
    "2020-08-31": 18353.3,
    "2020-09-30": 18570.8,
    "2020-10-31": 18731.3,
    "2020-11-30": 18964.5,
    "2020-12-31": 19118.9,
    "2021-01-31": 19367.2,
    "2021-02-28": 19610.6,
    "2021-03-31": 19848.9,
    "2021-04-30": 20104.5,
    "2021-05-31": 20411.0,
    "2021-06-30": 20451.7,
    "2021-07-31": 20605.0,
    "2021-08-31": 20824.2,
    "2021-09-30": 20955.9,
    "2021-10-31": 21133.8,
    "2021-11-30": 21338.4,
    "2021-12-31": 21478.1,
    "2022-01-31": 21640.7,
    "2022-02-28": 21699.2,
    "2022-03-31": 21739.0,
    "2022-04-30": 21643.6,
    "2022-05-31": 21646.8,
    "2022-06-30": 21602.0,
    "2022-07-31": 21635.0,
    "2022-08-31": 21636.8,
    "2022-09-30": 21516.7,
    "2022-10-31": 21432.3,
    "2022-11-30": 21400.6,
    "2022-12-31": 21236.2,
    "2023-01-31": 21267.1
  }
}

In [16]:
import pandas as pd
import requests

# set the start and end dates for the time period you want
start_date = '2019-08-28'
end_date = '2023-03-08'

# create an empty dataframe to store the data
economics = pd.DataFrame()

# loop through each API call and append the data to the dataframe
for function in ['INFLATION', 'REAL_GDP_PER_CAPITA', 'REAL_GDP', 'NONFARM_PAYROLL', 'BRENT']:
    url = f'https://www.alphavantage.co/query?function={function}&outputsize=full&apikey=XPPJ9T1WLPM2L360'
    r = requests.get(url)
    data = r.json()
    if "Error Message" in data.keys():
        print(f"Skipping API call for {function} due to error: {data['Error Message']}")
        continue
    col_name = list(data.keys())[1]  # the column name for the data
    df = pd.DataFrame.from_dict(data[col_name], orient='index')
    df.index = pd.to_datetime(df.index)  # convert index to datetime
    df = df[(df.index >= start_date) & (df.index <= end_date)]  # filter by date range
    df.columns = [f'{function}_{col}' for col in df.columns]  # rename columns to include function name
    economics = pd.concat([economics, df], axis=1)

# sort the dataframe by date
economics = economics.sort_index()

# print the first few rows of the dataframe
print(economics.head())

AttributeError: 'str' object has no attribute 'values'

In [21]:
import pandas as pd
import requests

# set the start and end dates for the time period you want
start_date = '2019-08-28'
end_date = '2023-03-08'

# replace 'YOUR_API_KEY' with your actual API key from Alpha Vantage
api_key = 'XPPJ9T1WLPM2L360'

# create an empty dataframe to store the data
economics = pd.DataFrame()

# loop through each API call and append the data to the dataframe
for function in ['INFLATION', 'REAL_GDP_PER_CAPITA', 'REAL_GDP', 'NONFARM_PAYROLL', 'BRENT']:
    url = f'https://www.alphavantage.co/query?function={function}&outputsize=full&apikey={api_key}'
    r = requests.get(url)
    data = r.json()
    col_name = list(data.keys())[1]  # the column name for the data
    df = pd.DataFrame.from_dict(data[col_name], orient='index')
    df.index = pd.to_datetime(df.index)  # convert index to datetime
    df = df[(df.index >= start_date) & (df.index <= end_date)]  # filter by date range
    df.columns = [f'{function}_{col}' for col in df.columns]  # rename columns to include function name
    economics = pd.concat([economics, df], axis=1)

# sort the dataframe by date
economics = economics.sort_index()

# print the first few rows of the dataframe
print(economics.head())

AttributeError: 'str' object has no attribute 'values'

In [22]:
import requests
import pandas as pd

# Set the start and end dates for the time period you want
start_date = '2019-08-28'
end_date = '2023-03-08'

# Define the symbols for the assets you want to retrieve
symbols = {
    'P225': '^N225',
    'S&P500': '^GSPC',
    'CSI300': '000300.SS',
    'DXY': 'DX-Y.NYB',
    'DJI': '^DJI',
    'Oil': 'CL=F',
    'NASDAQ': '^IXIC'
}

# Create an empty dataframe to store the data
prices = pd.DataFrame()

# Loop through each symbol and append the data to the dataframe
for symbol in symbols.values():
    url = "https://seeking-alpha.p.rapidapi.com/market/get-realtime-quotes"
    querystring = {"sa_ids": symbol}
    headers = {
        "X-RapidAPI-Key": "40d3a7f43cmshb0c6326b8f21b2cp1f3f76jsn6989f38dacf4",
        "X-RapidAPI-Host": "seeking-alpha.p.rapidapi.com"
    }
    response = requests.request("GET", url, headers=headers, params=querystring)
    data = response.json()['data'][0]
    df = pd.DataFrame(data, index=[pd.to_datetime(data['time'])])
    df = df[['last_price', 'volume']]
    df.columns = [f'{symbol}_{col}' for col in df.columns]
    prices = pd.concat([prices, df], axis=1)

# Filter the dataframe by date range
prices = prices[(prices.index >= start_date) & (prices.index <= end_date)]

# Sort the dataframe by date
prices = prices.sort_index()

# Print the first few rows of the dataframe
print(prices.head())

KeyError: 'data'

In [ ]:
import pandas as pd
import requests

start_date = '2019-08-28'
end_date = '2023-03-08'
api_key = 'XPPJ9T1WLPM2L360'

url = f'https://www.alphavantage.co/query?function=INFLATION&apikey={api_key}&start_date={start_date}&end_date={end_date}'
r = requests.get(url)
data = r.json()

# Extract the time series data from the JSON response
inflation_data = data['Time Series (Daily)']

# Convert the data to a pandas DataFrame
df = pd.DataFrame.from_dict(inflation_data, orient='index')

# Convert the data types of the columns to float
df = df.astype(float)

# Sort the DataFrame by date
df = df.sort_index()

print(df.head())

In [12]:
https://www.quandl.com/api/v3/databases?api_key=j1bxx9Kr2WVUiCkTus-u

SyntaxError: invalid syntax (3769135335.py, line 1)

In [11]:
import pandas as pd
import quandl

start_date = '2019-08-28'
end_date = '2023-03-08'
api_key = 'j1bxx9Kr2WVUiCkTus-u'

symbols = ['NIKKEI/INDEX', 'YAHOO/INDEX_GSPC', 'YAHOO/INDEX_DJI', 'NASDAQOMX/COMP', 'OPEC/ORB', 'USTREASURY/YIELD',
           'CME/CLJ21', 'CME/DXH21', 'SSE/000300']

dfs = []

for symbol in symbols:
    try:
        df = quandl.get(symbol, start_date=start_date, end_date=end_date, api_key=api_key)
        df.columns = [f'{symbol}_{c.lower()}' for c in df.columns]
        dfs.append(df)
    except quandl.errors.quandl_error.NotFoundError:
        print(f"Dataset {symbol} not found.")

Dataset NIKKEI/INDEX not found.
Dataset YAHOO/INDEX_GSPC not found.
Dataset YAHOO/INDEX_DJI not found.
Dataset CME/CLJ21 not found.
Dataset CME/DXH21 not found.
Dataset SSE/000300 not found.